---
title: "Week 11 lecture dev"
output: 
  html_notebook:
    toc: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=7, fig.height=5, fig.retina=3,
  out.width = "60%", fig.align = "center",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
knitr::opts_knit$set(root.dir = here::here())

library(tidyverse)
theme_set(theme_light())
library(extraDistr)
library(ggdist)
library(glue)
library(lme4)
library(lmerTest)

theme_update(text = element_text(size=16))

options(ggplot2.discrete.fill = RColorBrewer::brewer.pal(8, "Dark2"))
options(ggplot2.discrete.colour = RColorBrewer::brewer.pal(8, "Dark2"))
options(show.signif.stars = FALSE)
my_seed <- 8878
```

```{r}
sl <- read_csv("data/sl_data_postexclusions.csv")
zipfent <- read_csv("data/zipfent2_data_postexclusions.csv")
```

Let's see what interesting analyses we can do here.

# SL data

## Log RT ~ trial_idx

TODO: get series that increments by 1 for trial index instead of doing every third number starting at 305

```{r}
sl <- sl %>% 
  mutate(
    logRT = log(rt),
  )

sl %>% 
  ggplot(aes(x = trial_idx, y = logRT)) +
  geom_point() +
  geom_smooth(method = 'lm')
```

```{r}

```



