{
  "hash": "1e309af168aefec4d2038d530b3f005e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"When frequentist null-ritualistic and Bayesian regression give you opposite results\"\ndescription: \"Learn of the dangers of the null ritual in the context of regression models\"\nauthor: \"Stefano Coretta\"\ndate: 2024-11-28\nexecute: \n  freeze: auto\n---\n\n\n\n::: callout-warning\n## Prerequisites\n\n- [Introduction to regression models (Part III): include categorical predictors](intro-regression-categorical.qmd).\n:::\n\n\n\n\n\n\n\nAre there cases when a frequentist null-ritualistic and a Bayesian regression give opposite results in regression models? **YES**!\n\nIn the following example, we simulate data from two groups, A and B. In the population which A and B are sampled from, there is no difference between the two groups.\n\nIn our simulated sample, however, the mean of group A is 0 and that of group B is 4. This is clearly a quirk of the sample, since the mean of A and B should be the same.\n\nLet's say that our measurements contain some error, for example due to equipment limitations. We know that the measurement error of the equipment, based on the manufacturer's specification, is ±5. In the simulated data, we add random error to the observations (50 per group). Error is usually modelled as a Gaussian distribution with mean 0 and a specific standard deviation: here, we set the standard deviation (`error_sd`) to 4.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n# Set seed for reproducibility\nset.seed(707)\n\n# Observations per group\nn_per_group <- 50\ngroup <- rep(c(\"A\", \"B\"), each = n_per_group)\ntrue_diff <- 4\nerror_sd <- 4\n\ndata <- tibble(\n  group = rep(c(\"A\", \"B\"), each = n_per_group),\n  Y = c(\n    # Group A\n    rnorm(n_per_group, mean = 0, sd = error_sd),\n    # Group B\n    rnorm(n_per_group, mean = true_diff, sd = error_sd)\n  )\n)\ndata\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"group\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Y\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"A\",\"2\":\"-5.1274534\"},{\"1\":\"A\",\"2\":\"-2.4704437\"},{\"1\":\"A\",\"2\":\"2.7958574\"},{\"1\":\"A\",\"2\":\"4.5579942\"},{\"1\":\"A\",\"2\":\"-3.2886185\"},{\"1\":\"A\",\"2\":\"-4.1480475\"},{\"1\":\"A\",\"2\":\"8.2666357\"},{\"1\":\"A\",\"2\":\"1.7678767\"},{\"1\":\"A\",\"2\":\"-4.7311546\"},{\"1\":\"A\",\"2\":\"7.1620730\"},{\"1\":\"A\",\"2\":\"1.6746855\"},{\"1\":\"A\",\"2\":\"4.4868870\"},{\"1\":\"A\",\"2\":\"0.6641751\"},{\"1\":\"A\",\"2\":\"-3.5877884\"},{\"1\":\"A\",\"2\":\"-2.8666390\"},{\"1\":\"A\",\"2\":\"-4.6538122\"},{\"1\":\"A\",\"2\":\"6.0237748\"},{\"1\":\"A\",\"2\":\"1.5431172\"},{\"1\":\"A\",\"2\":\"0.2797623\"},{\"1\":\"A\",\"2\":\"4.2555142\"},{\"1\":\"A\",\"2\":\"-2.4317792\"},{\"1\":\"A\",\"2\":\"-3.8039345\"},{\"1\":\"A\",\"2\":\"0.1519096\"},{\"1\":\"A\",\"2\":\"0.4762532\"},{\"1\":\"A\",\"2\":\"3.1061104\"},{\"1\":\"A\",\"2\":\"9.0185559\"},{\"1\":\"A\",\"2\":\"-0.6643271\"},{\"1\":\"A\",\"2\":\"5.5221930\"},{\"1\":\"A\",\"2\":\"-1.9836975\"},{\"1\":\"A\",\"2\":\"1.8642101\"},{\"1\":\"A\",\"2\":\"2.4150938\"},{\"1\":\"A\",\"2\":\"5.0436252\"},{\"1\":\"A\",\"2\":\"3.7462610\"},{\"1\":\"A\",\"2\":\"-2.0496628\"},{\"1\":\"A\",\"2\":\"0.4320948\"},{\"1\":\"A\",\"2\":\"2.9694058\"},{\"1\":\"A\",\"2\":\"-1.2761049\"},{\"1\":\"A\",\"2\":\"-1.2685659\"},{\"1\":\"A\",\"2\":\"1.1120514\"},{\"1\":\"A\",\"2\":\"-0.1971719\"},{\"1\":\"A\",\"2\":\"-4.3209616\"},{\"1\":\"A\",\"2\":\"2.0652162\"},{\"1\":\"A\",\"2\":\"0.6818319\"},{\"1\":\"A\",\"2\":\"1.6095172\"},{\"1\":\"A\",\"2\":\"-3.8979666\"},{\"1\":\"A\",\"2\":\"-0.9064930\"},{\"1\":\"A\",\"2\":\"8.2899348\"},{\"1\":\"A\",\"2\":\"0.7898929\"},{\"1\":\"A\",\"2\":\"4.0178502\"},{\"1\":\"A\",\"2\":\"-1.9790574\"},{\"1\":\"B\",\"2\":\"4.7506326\"},{\"1\":\"B\",\"2\":\"4.9227076\"},{\"1\":\"B\",\"2\":\"-4.4125635\"},{\"1\":\"B\",\"2\":\"3.5106457\"},{\"1\":\"B\",\"2\":\"2.7700537\"},{\"1\":\"B\",\"2\":\"0.9874614\"},{\"1\":\"B\",\"2\":\"-0.1354450\"},{\"1\":\"B\",\"2\":\"8.2970847\"},{\"1\":\"B\",\"2\":\"0.3916286\"},{\"1\":\"B\",\"2\":\"1.3634314\"},{\"1\":\"B\",\"2\":\"14.3803011\"},{\"1\":\"B\",\"2\":\"3.2319892\"},{\"1\":\"B\",\"2\":\"3.3570230\"},{\"1\":\"B\",\"2\":\"0.8630915\"},{\"1\":\"B\",\"2\":\"1.4311202\"},{\"1\":\"B\",\"2\":\"2.4595505\"},{\"1\":\"B\",\"2\":\"7.7014074\"},{\"1\":\"B\",\"2\":\"3.6584021\"},{\"1\":\"B\",\"2\":\"2.3363910\"},{\"1\":\"B\",\"2\":\"0.4859458\"},{\"1\":\"B\",\"2\":\"3.3239597\"},{\"1\":\"B\",\"2\":\"8.8723950\"},{\"1\":\"B\",\"2\":\"10.5210275\"},{\"1\":\"B\",\"2\":\"6.3334712\"},{\"1\":\"B\",\"2\":\"6.6222179\"},{\"1\":\"B\",\"2\":\"-4.3459678\"},{\"1\":\"B\",\"2\":\"1.4670911\"},{\"1\":\"B\",\"2\":\"2.1990833\"},{\"1\":\"B\",\"2\":\"10.4082632\"},{\"1\":\"B\",\"2\":\"0.6926614\"},{\"1\":\"B\",\"2\":\"5.3883372\"},{\"1\":\"B\",\"2\":\"2.0435300\"},{\"1\":\"B\",\"2\":\"7.5119843\"},{\"1\":\"B\",\"2\":\"4.0344669\"},{\"1\":\"B\",\"2\":\"6.5900990\"},{\"1\":\"B\",\"2\":\"5.7570448\"},{\"1\":\"B\",\"2\":\"3.4515427\"},{\"1\":\"B\",\"2\":\"5.3542787\"},{\"1\":\"B\",\"2\":\"6.6920578\"},{\"1\":\"B\",\"2\":\"9.9582606\"},{\"1\":\"B\",\"2\":\"8.6650351\"},{\"1\":\"B\",\"2\":\"-2.7173171\"},{\"1\":\"B\",\"2\":\"4.2765028\"},{\"1\":\"B\",\"2\":\"2.3127372\"},{\"1\":\"B\",\"2\":\"3.7056914\"},{\"1\":\"B\",\"2\":\"0.8751858\"},{\"1\":\"B\",\"2\":\"5.9761774\"},{\"1\":\"B\",\"2\":\"5.1885109\"},{\"1\":\"B\",\"2\":\"13.2568282\"},{\"1\":\"B\",\"2\":\"4.7171347\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\nLet's plot the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  ggplot(aes(group, Y)) +\n  geom_jitter(width = 0.1) +\n  # Mean with 95% CIs\n  stat_summary(fun.data = function(x) mean_se(x, 1.96), colour = \"purple\")\n```\n\n::: {.cell-output-display}\n![](regression-freq-bayes_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\nWe know that the difference we see in the sample is due to error, not to a real difference between A and B.\n\nNow, let's run a frequentist (null-ritualistic) regression with `lm()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_model <- lm(Y ~ group, data = data)\n\nsummary(lm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ group, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.6422 -2.8030 -0.2708  2.3026 10.1506 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   0.8227     0.5373   1.531    0.129    \ngroupB        3.4069     0.7598   4.484 1.99e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.799 on 98 degrees of freedom\nMultiple R-squared:  0.1702,\tAdjusted R-squared:  0.1618 \nF-statistic: 20.11 on 1 and 98 DF,  p-value: 1.993e-05\n```\n\n\n:::\n:::\n\n\n\nIf you look at the *p*-value of `groupB`, it is lower than 0.05, so according to this model there is a significant difference between A and B.\n\nLet's now fit a Bayesian regression.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\nbrm_model <- brm(\n  Y ~ group,\n  data = data,\n  seed = 707, file = \"cache/regression-freq-bayes_brm_model\"\n)\n\nsummary(brm_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: Y ~ group \n   Data: data (Number of observations: 100) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     0.82      0.53    -0.22     1.85 1.00     3936     2966\ngroupB        3.39      0.77     1.91     4.86 1.00     3900     3033\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     3.82      0.28     3.34     4.41 1.00     3427     2615\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\nLook at the 95% CrI of `groupB`: it's [1.91, 4.86].\n\nAbove we said that the equipment error is ±5. This can be thought of as a \"Region of Practical Equivalence\" (ROPE): any difference greater than or equal to -5 and smaller than or equal to +5 is practically equivalent to \"no difference\", since we know that the equipment is not sensitive enough to be able to record differences that are within that range.\n\nThe CrI of `groupB` is fully within the ROPE [-5, +5]. Thus, based on the Bayesian model we (correctly) infer that there is no difference in A and B in the population we sampled from.\n\n**To summarise, the frequentist model incorrectly reported a significant difference, while we know the population does not have this difference.**\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}