project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!slides/"
    - "!tutorials/"
    - "!data/"
    - "!static/"
  resources:
    - "slides/"
    - "img/"
    - "data/"
    - "static/"
    - ".nojekyll"

website:
  title: "QML"
  navbar:
    background: dark
    tools:
      - icon: github
        href: "https://github.com/uoelel/qml"
    left:
      - href: index.qmd
        text: Home
      - href: content.qmd
        text: Content
      - href: lectures.qmd
        text: Lectures
      - href: workshops.qmd
        text: Workshops
      - href: assessments.qmd
        text: Assessment
      - href: https://stefanocoretta.github.io/qdal/
        text: Textbook

format:
  html:
    theme: united
    css: styles.css
    toc: true
    df-print: paged
    number-sections: true
    embed-resources: false
    fig-align: center
    link-external-icon: true
    link-external-newwindow: true

callout-icon: false

execute:
  freeze: auto
