project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!slides/"
    - "!tutorials/"
    - "!data/"
  resources:
    - "slides/"
    - "img/"
    - "data/"

website:
  title: "QML"
  navbar:
    background: dark
    tools:
      - icon: github
        href: "https://github.com/uoelel/qml"
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Course schedule
      - href: map.qmd
        text: Map
      - href: notebook.qmd
        text: Notebook
      - href: challenges.qmd
        text: Challenges
      - href: assessments.qmd
        text: Assessment
      - href: extra.qmd
        text: Extra

format:
  html:
    theme: united
    css: styles.css
    toc: true
    df-print: paged
    number-sections: true
    embed-resources: false
    fig-align: center

callout-icon: false

execute:
  freeze: true
  cache: true
