## Schedule overview

| Week       | Topic                                |                       |                                        |     |     |
|-----------|--------------|--------|---------|-----------------|--------------|
| 1          | Quantitative methods and uncertainty | [Slides](slides/w01/) | [Tutorial](tutorials/tutorial-w01.qmd) |     |     |
| 2          | Data wrangling                       | [Slides](slides/w02/) | [Tutorial](tutorials/tutorial-w02.qmd) |     |     |
| 3          | Data visualisation                   | [Slides](slides/w03/) | [Tutorial](tutorials/tutorial-w03.qmd) |     |     |
| 4          | Statistical modeling basics          | [Slides](slides/w04/) | [Tutorial](tutorials/tutorial-w04.qmd) |     |     |
| 5          | Categorical predictors               | [Slides](slides/w05/) | [Tutorial](tutorials/tutorial-w05.qmd) | F1  |     |
| 6 Catch up | *No classes*                         |                       |                                        |     |     |
| 7          | Binary outcomes                      | [Slides](slides/w07/) | [Tutorial](tutorials/tutorial-w07.qmd) |     |     |
| 8          | Multiple predictors and interactions | [Slides](slides/w08/) | [Tutorial](tutorials/tutorial-w08.qmd) |     | S1  |
| 9          | Continuous predictors                | [Slides](slides/w09/) | [Tutorial](tutorials/tutorial-w09.qmd) |     |     |
| 10         | Bayesian inference                   | [Slides](slides/w10/) | [Tutorial](tutorials/tutorial-w10.qmd) | F2  |     |
| 11         | Obtaining p-values (optional)        | [Slides](slides/w11/) | [Tutorial](tutorials/tutorial-w11.qmd) |     |     |
| 12         |                                      |                       |                                        |     | S2  |

## Weekly schedule

### Week 1: Quantitative methods and uncertainty

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   What is quantitative data analysis?
-   What is the inference process?
-   How can we talk about uncertainty and variability?
-   Which are the limits of quantitative methods?

**Skills**

-   Think critically about statistics, uncertainty and variability.
-   Use R to perform simple calculations.
-   Master the basics of the programming language R.
-   Use RStudio.
:::

::: {.callout-note collapse="true"}
#### Homework

**Intake form**

-   **You must complete the intake form before coming to the Tuesday lecture.**
-   The link to the form will be circulated via Learn.

**Install R and RStudio**

-   For this course, you need to install both R and RStudio.
-   **NOTE**: If you have installed either R or RStudio prior to January 2023, please make sure you delete both R and RStudio from your laptop.
-   Please, follow the instructions in the [Setup](setup.qmd) page.
:::

::: {.callout-tip collapse="true"}
#### Materials

-   [Lecture slides](slides/w01/).
-   [Workshop tutorial](tutorials/tutorial-w01.qmd).
:::

::: {.callout-tip collapse="true"}
#### Suggested readings

**Main textbooks**

-   Statistics for Linguists with R, by Bodo Winter (**S4LR**) Ch. 1. \[via library\]
-   R for Data Science (**R4DS**) [Ch. 1](https://r4ds.had.co.nz/introduction.html), [Ch. 2](https://r4ds.had.co.nz/explore-intro.html). \[online book\]
-   Statistical (Re)thinking, by Richard McElreath (**SReT**), Ch. 1. \[via library\]

**Papers**

-   [Darwin Holmes 2020](https://doi.org/10.34293/education.v8i4.3232). Researcher Positionality - A Consideration of Its Influence and Place in Qualitative Research - A New Researcher Guide
-   [Jafar 2018](https://doi.org/10.1136/emermed-2017-207158). What is positionality and should it be expressed in quantitative studies?

**From the lecture**

-   [Silberzahn et al. 2018](https://doi.org/10.1177/2515245917747646). Many Analysts, One Data Set: Making Transparent How Variations in Analytic Choices Affect Results
-   [Coretta et al. (in principle)](https://doi.org/10.31234/osf.io/q8t2k). Multidimensional signals and analytic flexibility: Estimating degrees of freedom in human speech analyses
-   [Cumming 2014](https://doi.org/10.1177%2F0956797613504966). The New Statistics: Why and How
-   [Kurschke and Liddell 2018](https://doi.org/10.3758/s13423-016-1221-4). The Bayesian New Statistics: Hypothesis testing, estimation, meta-analysis, and power analysis from a Bayesian perspective
:::

### Week 2: Data wrangling

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   What are the types of statistical variables?
-   Which summary measures are appropriate for which types of variables?
-   What are common measures central tendency?
-   What are common measures of dispersion?

**Skills**

-   Organise files efficiently.
-   Import tabular data in R.
-   Obtain mean, median, mode, range and standard deviation.
-   Use R scripts to save and reuse code.
:::

::: {.callout-tip collapse="true"}
#### Materials

-   [Lecture slides](slides/w02/).
-   [Workshop tutorial](tutorials/tutorial-w02.qmd).
-   Workshop files (right-click and download):
    -   [shallow.csv](data/shallow.csv)
:::

::: {.callout-tip collapse="true"}
#### Suggested readings

**Main textbooks**

-   **S4LR** Ch. 3. \[via library\]
-   **R4DS** [Ch. 4](https://r4ds.had.co.nz/workflow-basics.html) and [Ch. 5](https://r4ds.had.co.nz/transform.html). \[online book\]
:::

### Week 3: Data visualisation

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   What are the principles of good data visualisation?
-   Which are the main components of a plot?
-   Which are the appropriate plots for different types of data?
-   How can we visualise uncertainty?

**Skills**

-   Create common types of plots with ggplot2.
-   Use colour and shape to effectively convey meaning.
-   Describe a plot in writing and comment on observable patterns.
-   Create styled HTML reports.
:::

::: {.callout-tip collapse="true"}
#### Materials

-   [Lecture slides](slides/w03/).
-   [Workshop tutorial](tutorials/tutorial-w03.qmd).
-   Workshop files (right-click and download):
    -   [polite.csv](data/polite.csv)
    -   [glot_status.rds](data/glot_status.rds)
:::

::: {.callout-tip collapse="true"}
#### Suggested readings

**Main textbooks**

-   **R4DS** [Ch. 3](https://r4ds.had.co.nz/data-visualisation.html). \[online book\]
-   [ggplot2](https://ggplot2.tidyverse.org) documentation.

**From the lecture**

-   [Spiegelhalter 2020](https://www.penguin.co.uk/books/294857/the-art-of-statistics-by-spiegelhalter-david/9780241258767). *The Art of Statistics: Learning from Data.*

**Extra**

-   [Fundamentals of Data Visualisation](https://clauswilke.com/dataviz/).
-   **Data viz catalogues**
    -   [Directory of visualisations](https://clauswilke.com/dataviz/directory-of-visualizations.html)
    -   [Data viz catalogue](https://datavizcatalogue.com/index.html)
    -   [Data Viz project](https://datavizproject.com)
    -   [Top 50](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
    -   [Data Viz](https://datavizm20.classes.andrewheiss.com/)
-   **Tutorials**
    -   [Raincloud plots](https://wellcomeopenresearch.org/articles/4-63)
    -   [Labels](https://www.cararthompson.com/talks/user2022/)
    -   [Graphic design](https://rstudio-conf-2022.github.io/ggplot2-graphic-design/)
-   **Colour**
    -   [ColorBrewer2](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3).
    -   [MetBrewer](https://github.com/BlakeRMills/MetBrewer)
    -   [Use colour wisely](https://albert-rapp.de/post/2022-02-19-ggplot2-color-tips-from-datawrapper/).
-   **Caveats**
    -   [Same stats different data](https://www.autodesk.com/research/publications/same-stats-different-graphs).
    -   [Behind bars](https://stats.stackexchange.com/questions/349422/does-it-make-sense-to-add-error-bars-in-a-bar-chart-of-frequencies/367889#367889).
    -   [Issues with error bars](https://www.data-to-viz.com/caveat/error_bar.html).
    -   [I've stopped using boxplots](https://nightingaledvs.com/ive-stopped-using-box-plots-should-you/).
:::

### Week 4: Statistical modeling basics

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   What are probability distributions?
-   How can we describe probability distributions with statistical parameters?
-   What are the frequentist and Bayesian view of statistical parameters?
-   How can we estimate parameters using statistical models?

**Skills**

-   Transform data by creating new columns (mutate) and filtering based on specific values (filter).
-   Use logical operators to transform data.
-   Fit a statistical model to estimate the mean and standard deviation of a Gaussian variable with `brm()`.
-   Interpret the summary of the model and understand the meaning of the reported estimates.
:::

::: {.callout-tip collapse="true"}
#### Materials

-   [Lecture slides](slides/w04/).
-   [Workshop tutorial](tutorials/tutorial-w04.qmd).
-   Workshop files (right-click and download):
    -   [alb_vot.csv](data/alb_vot.csv)
:::

::: {.callout-tip collapse="true"}
#### Suggested readings

**Main textbooks**

-   **R4DS** [Ch. 3](https://r4ds.had.co.nz/data-visualisation.html). \[online book\]
-   [ggplot2](https://ggplot2.tidyverse.org) documentation.
-   **S4LR** Ch 3. \[via library\]
-   **SReT** Ch 2, sparingly (we have not covered everything in the chapter yet). \[via library\]
:::

### Week 5: Categorical predictors

::: {.callout-warning collapse="true"}
#### Formative assessment 1

-   \*\*DUE on Thu 19 October at noon\*.

-   Formative assessment 1 requires you to complete a few guided exercises of the type that will be included in Summative 1.
:::

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   How do we model variables using categorical predictors?
-   Which are the most common coding systems for categorical predictors?
-   How do we interpret the model output when there are categorical predictors?
-   How can we quickly check model goodness?

**Skills**

-   Master contrast coding in R for categorical predictors.
-   Understand treatment coding.
-   Fit, interpret and plot models with a categorical predictor.
-   Reporting of model specification and results.
:::

::: {.callout-tip collapse="true"}
#### Materials

-   [Lecture slides](slides/w05/).
-   [Workshop tutorial](tutorials/tutorial-w05.qmd).
-   Workshop files (right-click and download):
    -   [senses_valence.csv](data/senses_valence.csv)
:::

::: {.callout-tip collapse="true"}
#### Suggested readings

**Main textbooks**

-   **R4DS** [Ch. 15](https://r4ds.had.co.nz/factors.html). \[online book\]
-   **S4LR** Ch 7. \[via library\]
-   **SReT** Sec 5.3. \[via library\]
:::

### Week 6: Catch-up Week

::: {.callout-note collapse="true"}
#### Homework

There is no homework as such, so take the time to revise the materials and/or catch up with the previous weeks' materials.

There will be no classes.
:::

### Week 7: Binary outcomes

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   How can we visualise proportions of binary outcomes (yes/no, correct/incorrect, ...)?
-   Which distribution do binary outcomes follow?
-   What is the relationship between probabilities and log-odds?
-   How do we interpret log-odds and odds?

**Skills**

-   Plot binary data as proportions in ggplot2.
-   Pivot data from wide to long with tidyr.
-   Fit, interpret and plot linear models with binary outcome variables, using the Bernoulli distribution family.
-   Convert between log-odds, odds and probabilities.
:::

::: {.callout-tip collapse="true"}
#### Materials

-   [Lecture slides](slides/w07/).
-   [Workshop tutorial](tutorials/tutorial-w07.qmd).
-   Workshop files (right-click and download):
    -   [takete_maluma.txt](data/takete_maluma.txt).
:::

### Week 8: Multiple predictors and interactions

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   What is a factorial design?
-   How do we estimate and interpret the effects of multiple predictors?
-   How do we deal with situations when one predictor's effect is different, depending on the value of the other predictor?
-   How can such interactions between predictors be built into our models?
-   How do we interpret model estimates of interactions?

**Skills**

-   Run and interpret models with multiple predictors.
-   Interpret interactions between two predictors.
-   Plot posterior and conditional probabilities from models with interactions.
-   Practice transforming and back-transforming variables.
:::

::: {.callout-tip collapse="true"}
#### Materials

-   [Lecture slides](slides/w08/).
-   [Workshop tutorial](tutorials/tutorial-w08.qmd).
-   Workshop files (right-click and download):
    -   [shallow.csv](data/shallow.csv).
    -   [dur-ita-pol.csv](data/dur-ita-pol.csv).
:::

### Week 9: Continuous predictors and interactions

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   How do we model predictors that aren't categorical, but continuous?
-   How do we interpret model estimates for continuous predictors?
-   How do we fit and interpret interactions involving continuous predictors?

**Skills**

-   Centre continuous predictors.
-   Run and interpret models with continuous predictors.
-   Interpret interactions that are categorical \* continuous (in the lecture) and continuous \* continuous (in the tutorial).
:::

::: {.callout-tip collapse="true"}
#### Materials

-   [Lecture slides](slides/w09/).
-   [Workshop tutorial](tutorials/tutorial-w09.qmd).
-   Workshop files (right-click and download):
    -   [si.csv](data/si.csv).
:::

### Week 10: Bayesian inference

::: {.callout-warning collapse="true"}
#### Formative assessment 2

-   **DUE on Thursday 23 November at noon**.

-   F2 requires you to read, plot and model data. Summative 2 will have the same format.
:::

### Week 11: Obtaining *p*-values (Optional)

```{=html}
<!--
### Thursday 30 March

::: {.callout-warning collapse="true"}
#### Summative assessment 1

**Due on Thursday 30 March at noon**

The first summative contains a series of guided exercises. You can find the summative materials and exercises here: <https://github.com/uoelel/qml-s1>.

You may find helpful information in the FAQ post on Piazza [here](https://piazza.com/class/lcns7m75s8pdw/post/63).
:::

### Thursday 27 April

::: {.callout-warning collapse="true"}
#### Summative assessment 2

**Due on Thursday 27 April at noon**

In the second summative assessment, you will:

-   select a dataset and its associated research questions,
-   analyse the data using one linear model, and
-   write a report about the data, the model, and your findings.

You can find more information about the assessment on GitHub here: <https://github.com/uoelel/qml-s2>
:::
-->
```
