---
title: "Extra resources"
author: "Stefano Coretta"
---

This page lists vetted resources for learning statistics with R if you would like to learn more about certain topics (or also as alternative materials to the [Notebook](notebook.qmd)).

## Recommended textbooks

These are recommended textbooks for beginners. The topics covered in this course are based on these textbooks.

-   [R for Data Science](https://r4ds.hadley.nz) \[R4DS\]. This is an introduction to R and the tidyverse packages.

-   [Statistical (Re)thinking](https://discovered.ed.ac.uk/permalink/44UOE_INST/110jsec/alma9924745740602466). This is a textbook that teaches statistics in R with a focus on Bayesian regression modelling. It is meant for beginners but intermediate and advanced users can benefit from the later chapters.

-   [Statistics for Linguists](https://discovered.ed.ac.uk/permalink/44UOE_INST/7g3mt6/alma9924344853202466). This is a textbook that teaches statistics in R with a focus on frequentist regression modelling. It is meant for beginners but intermediate and advanced users can benefit from the later chapters.

For papers that use or argue for the use of Bayesian regression models in different disciplines within linguistics, see [Bayesian regression in linguistic research](posts/bayes-papers.qmd).

## R skills

- The [Data analysis](https://uoelel.github.io/analysis.html) page of the [Data Analysis @ UoE LEL](https://uoelel.github.io) website contains an extended list of books and papers on different statistical topics in R. Also check the [Research Skills](https://uoelel.github.io/skills.html) page and the [Software](page) for non-strictly R stuff.

-   [Text mining with R](https://www.tidytextmining.com). It introduces readers to text mining in R using the [tidytext](<https://github.com/juliasilge/tidytext>) package which works well with tidyverse packages.

-  [Hands-on Machine Learning with R](https://bradleyboehmke.github.io/HOML/) and [Introduction to Machine Learning with R](https://discovered.ed.ac.uk/permalink/44UOE_INST/7g3mt6/alma9925334736002466).

## Philosophy of science

- [Philosophy of science: very short introduction](https://doi.org/10.1093/actrade/9780192802835.001.0001).

- [Understanding psychology as a science](https://www.bloomsbury.com/uk/understanding-psychology-as-a-science-9780230542310/).

- [Modeling Mindsets](https://christophmolnar.com/books/modeling-mindsets/). A book on "world-views behind various statistical modeling and machine learning mindsets."
