---
title: "The Schedule"
editor: visual
---

## Choose your own adventure

The course is structured in a "**choose your own adventure**" format, so there isn't a set content for each week.

::: callout-important
**Each week**, you will attend two classes:

-   A **one-hour seminar**.

-   A **two-hour lab**.

Note that you are *divided in two groups*, so that the seminar and lab run twice each week, you just need to attend one of the seminars and one of the labs each week.
:::

The **seminars** will have a different major theme each week, which you will have to research before class and discuss in groups in class.

**You are also expected to learn quantitative methods outside of class**, at your own time (as in a flipped classroom). This website has a list of entries in the Adventurer's [Notebook](notebook.qmd). You are not restricted to those posts, and you can learn from other resources, however if this is the very first time you are learning quantitative methods I recommend you stick to those since they have been curated for beginners. You can find a map of how the different posts build on each other in the Adventurer's [Map](map.qmd).

The **labs** will create the opportunity for you to practice quantitative data analysis with R. Each week you will pick a "challenge" from a list or come up with your own challenge and work towards solving it using R. More details will be shared soon.

As part of the [Assessments](assessments.qmd), you will have to complete a **group project**. You can start working on the project any time during the course, but the last two labs will be dedicated to working on your project while being able to get help from the instructor (Stefano) and the Tutors.

## Schedule overview

The following tables gives you an approximate schedule of the weekly themes, although they are subject to change also in light of your preferences. Check the week-by-week boxes below for a more detailed description of what you should be doing each week.

| Week | Seminar | Lab |
|-------|--------------------------------------|------------------------------------------|
| 1 | Welcome and practicalities | Notebook: [Learn the basics of R](posts/r-basics.qmd) |
| 2 | [More than numbers: quantitative methods and uncertainty](discussions/discussion-02.qmd) | [Challenge](challenges.qmd) |
| 3 | [Language endangerment and small numbers](discussions/discussion-03.qmd) | [Challenge](challenges.qmd) |
| 4 | [Language technology and big data](discussions/discussion-04.qmd) | [Challenge](challenges.qmd) |
| 5 | [The research process: research ethics and questionable practices](discussions/discussion-05.qmd) | Challenge: [Statistical modelling](challenges/regression.qmd) |
| 6 | [The language of the climate crisis](discussions/discussion-06.qmd) | [Challenge](challenges.qmd) |
| 7 | [Equality, diversity and inclusiveness in quantitative linguistics](discussions/discussion-07.qmd) | [Challenge](challenges.qmd) |
| 8 | [Mindless statistics](discussions/discussion-08.qmd) | [Challenge](challenges.qmd) |
| 9 | [Open research and scholarship](discussions/discussion-09.qmd) | Challenge: Communicate your research |
| 10 | What's next? | Group project |
| 11 | Reflect on what you learnt | Group project |

## Recommended textbooks

There isn't a required course textbook as such, but the majority of the course content are covered in the [recommended textbooks](extra.qmd#recommended-textbooks).

## Weekly breakdown

::: {.callout-note collapse="true"}
#### Week 1

**In the seminar**

-   Come to the seminar class. We will go through the course format, assessment and other practicalities.

**In your own time**

-   Carefully read the [homepage](index.qmd) of the Course website.

-   Complete the Intake Form (the link to the form can be found on the Learn website).

-   **Install R, RStudio and Quarto:** please, follow the instructions in the [Setup](setup.qmd) page. You should do this *before the first lab class*.

-   Write your weekly self-reflection.

**In the lab**

-   Come to the lab class. Learn about the [basics of R](posts/r-basics.qmd). Optionally, if you need to freshen up your computer basics, you can check [Basic computer literacy](posts/computer-basics.qmd).
:::

::: {.callout-note collapse="true"}
#### Week 2

**In your own time**

-   Read [Research methods and hodotics](posts/hodotics.qmd), [Read data in R](posts/data-types.qmd) (make sure you read the pre-requisites too!).

-   Watch [The Golem of Prague](https://youtu.be/FdnMWdICdRs?si=BLyz4G19T5elt_ho). And/or read the related chapter of *Statistical Rethinking*, [The Golem of Prague](https://discovered.ed.ac.uk/permalink/44UOE_INST/19s2m21/cdi_proquest_ebookcentralchapters_6133700_13_20).

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd).

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - [Quantitative methods and uncertainty](discussions/discussion-02.qmd).

**In the lab**

-   Group activity: pick a [Challenge](challenges.qmd).
:::

::: {.callout-note collapse="true"}
#### Week 3

**In your own time**

-   Read [Research questions and hypotheses](posts/research-qh.qmd), [Summary measures](posts/summaries.qmd) and [Wrangling data with R](posts/wrangle.qmd) (make sure you read the pre-requisites too!).

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd).

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - [Language endangerment and small numbers](discussions/discussion-03.qmd).

**In the lab**

-   Group activity: pick a [Challenge](challenges.qmd) or continue working on one.
:::

::: {.callout-note collapse="false"}
#### Week 4

**In your own time**

-   Read [Inference and uncertainty](posts/inference.qmd) and [Plotting basics](posts/plotting-basics.qmd) (make sure you read the pre-requisites too!).

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd). Feel free to read from any other source, including the recommended textbooks.

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - [Language technology and big data](discussions/discussion-04.qmd)

**In the lab**

-   Group activity: pick a [Challenge](challenges.qmd) or continue working on one.
:::

::: {.callout-note collapse="true"}
#### Week 5

**BEFORE THE SEMINAR**

-   Read [Measuring the Prevalence of Questionable Research Practices With Incentives for Truth Telling](https://doi.org/10.1177/0956797611430953).

-   Read [Reproducibility and replicability](./posts/repro-repli.qmd)

**In your own time**

-   Read [Introduction to regression models (Part I)](posts/intro-regression.qmd) (make sure you read the pre-requisites too!).

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd). Feel free to read from any other source, including the recommended textbooks.

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - [The research process: research ethics and questionable practices](discussions/discussion-05.qmd)

**In the lab**

-   Group activity: [Statistical modelling](challenges/regression.qmd)
:::

::: {.callout-note collapse="true"}
#### Week 6

**In your own time**

-   Read [Regression: categorical predictors](posts/intro-regression-categorical.qmd) (make sure you read the pre-requisites too!).

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd). Feel free to read from any other source, including the recommended textbooks.

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - [The language of the climate crisis](discussions/discussion-06.qmd)

**In the lab**

-   Group activity: pick a [Challenge](challenges.qmd) or continue working on one.
:::

::: {.callout-note collapse="true"}
#### Week 7

**In your own time**

-   I recommend LEL students doing a dissertation this year to continue reading the entries on regression modelling for the rest of the course, because the vast majority of dissertation projects in linguistics entail statistical modelling using some type of regression. Feel free to book Stefano for a chat on specific topics depending on the area of research of your dissertation.

-   Read [Frequentist statistics and p-values](posts/p-values.qmd)

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd). Feel free to read from any other source, including the recommended textbooks.

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - [Equality, diversity and inclusiveness in quantitative linguistics](discussions/discussion-07.qmd)

**In the lab**

-   Group activity: pick a [Challenge](challenges.qmd) or continue working on one.
:::

::: {.callout-note collapse="true"}
#### Week 8

**In your own time**

-   Read [Mindless statistics](https://www.doi.org/10.1016/j.socec.2004.09.033).

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd). Feel free to read from any other source, including the recommended textbooks.

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - [Mindless statistics](discussions/discussion-08.qmd)

**In the lab**

-   Group activity: pick a [Challenge](challenges.qmd) or continue working on one.
:::

::: {.callout-note collapse="true"}
#### Week 9

**BEFORE THE SEMINAR**

-   Read [Seven easy steps to open science: an annotated reading list](https://www.doi.org/10.1027/2151-2604/a000387).

-   Read [The benefits of an open-science approach in student research projects](https://www.doi.org/10.1042/bio_2021_198).

**In your own time**

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd). Feel free to read from any other source, including the recommended textbooks.

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - [Open research and scholarship](discussions/discussion-09.qmd)

**In the lab**

-   Group activity: pick a [Challenge](challenges.qmd) or continue working on one.
:::

::: {.callout-note collapse="true"}
#### Week 10

**In your own time**

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd). Feel free to read from any other source, including the recommended textbooks.

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - What's next?

**In the lab**

-   Group activity: work on your Group Project.
:::

::: {.callout-note collapse="true"}
#### Week 11

**In your own time**

-   Pick and read any other entry/ies from the [Notebook](notebook.qmd). Feel free to read from any other source, including the recommended textbooks.

-   Write your weekly self-reflection.

**In the seminar**

-   Group discussion - Reflect on what you learnt.

**In the lab**

-   Group activity: work on your Group Project.
:::
