{
  "hash": "30ec6b8ae20739939bbefa6e8bae1cb8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"QML - Week 5\"\nsubtitle: \"Regression models: the basics\"\nauthor: \"Stefano Coretta\"\nformat: revealjs\nbibliography: references.bib\n---\n\n## Word frequency and reaction times\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n**What is the relationship between a word's lexical frequency and reaction times in a lexical decision task in Croatian?**\n:::\n\n. . .\n\n::: {.callout-note appearance=\"simple\"}\n-   Data from [Lexical decision times for nouns from the Croatian Psycholinguistic Database](https://data.crossda.hr/dataset.xhtml?persistentId=doi:10.23669/EV3NFJ&version=2.0).\n\n-   Lexical decision task (*is it a real Croatian word?*)\n\n    -   **Reaction times**.\n\n    -   **Word frequency**: counts from the Croatian web Corpus *hrWaC*.\n:::\n\n## Group activity\n\n::::: columns\n::: {.column width=\"75%\"}\n```{=html}\n<iframe allowfullscreen frameborder=\"0\" height=\"100%\" mozallowfullscreen style=\"min-width: 500px; min-height: 355px\" src=\"https://app.wooclap.com/events/EIZPEY/questions/68be9c5d60c14c53a7fc9db4\" width=\"100%\"></iframe>\n```\n:::\n\n::: {.column width=\"25%\"}\n```{=html}\n<iframe style=\"width:100%;max-width:360px;height:360px;\"\n                    src=\"https://stopwatch-app.com/widget/timer?theme=light&color=indigo&hrs=0&min=5&sec=0\" \n                    frameborder=\"0\"></iframe>\n```\n:::\n:::::\n\n## The data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncroat <- read_csv(\"data/vlasicek2024/croatian-lexdes.csv\")\ncroat |> select(word_string, rt_milliseconds_mean, word_frequency)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,612 × 3\n   word_string  rt_milliseconds_mean word_frequency\n   <chr>                       <dbl>          <dbl>\n 1 ribnjak                      575.           5755\n 2 dostupnost                   624.          15564\n 3 deformacija                  706.           6016\n 4 antioksidans                 914.           7646\n 5 zapis                        623.          44327\n 6 kvadrat                      549.          36394\n 7 presedan                     987.           7786\n 8 zapremnina                  1035.           1434\n 9 prerada                      750.          18759\n10 general                      625.          96640\n# ℹ 2,602 more rows\n```\n\n\n:::\n:::\n\n\n## Reaction times\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/rts-plot-1.png){width=960}\n:::\n:::\n\n\n## Word frequency\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/freq-plot-1.png){width=960}\n:::\n:::\n\n\n## Word frequency: logged\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/freq-log-plot-1.png){width=960}\n:::\n:::\n\n\n## Word frequency and RTs\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/rt-freq-plot-1.png){width=960}\n:::\n:::\n\n\n## Gaussian model of RT\n\n$$\nRT \\sim Gaussian(\\mu, \\sigma)\n$$\n\n. . .\n\n::: {.callout-important appearance=\"simple\"}\nBut we want to know what happens to RTs depending on the value of lexical frequency...\n:::\n\n. . .\n\n::: {.callout-tip appearance=\"simple\"}\nThen we let the mean $\\mu$ vary by lexical frequency!\n:::\n\n$$\n\\begin{align}\nRT & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & = \\beta_0 + \\beta_1 \\cdot logf\n\\end{align}\n$$\n\n. . .\n\n::: {.callout-important appearance=\"simple\"}\nBut what are those $\\beta_0$ and $\\beta_1$?\n:::\n\n## The equation of a line\n\n$$\ny = a + b \\cdot x\n$$\n\n::: {.callout-note appearance=\"simple\"}\n-   $a$ is the line **intercept**: the $y$ value when $x$ is `0` zero.\n\n-   $b$ is the line **slope**: the change in $y$ for each unit-increase of $x$.\n:::\n\n## Intercept\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/int-plot-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Slope\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/slo-plot-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## The equation of a line (bis)\n\n$$\ny = a + b \\cdot x\n$$\n\n::: {.callout-note appearance=\"simple\"}\n-   $a$ is the line **intercept**: the $y$ value when $x$ is `0` zero.\n\n-   $b$ is the line **slope**: the change in $y$ for each unit-increase of $x$.\n:::\n\n. . .\n\n$$\ny = \\beta_0 + \\beta_1 \\cdot x\n$$\n\n\\[alternative notation\\]\n\n## Regression model\n\n$$\n\\begin{align}\nRT & \\sim Gaussian(\\mu, \\sigma)\\\\\n\\mu & = \\beta_0 + \\beta_1 \\cdot logf & \\text{[Regression equation]}\n\\end{align}\n$$\n\n::: {.callout-tip appearance=\"simple\"}\n-   A **regression model** is a model based on the equation of a line.\n\n-   The model **estimates** $\\beta_0$ (the intercept) and $\\beta_1$ (the slope) from the data (i.e. the observed $RT$ and $logf$ values).\n:::\n\n. . .\n\n::: {.callout-note appearance=\"simple\"}\n-   $\\beta_0$, intercept\n\n    -   Mean RT value *when logged frequency is `0` zero* (i.e. when word frequency is 1; `exp(0)` = 1).\n\n-   $\\beta_1$, slope\n\n    -   *Change* in mean RT for each unit increase of log-frequency (when log-frequency goes from $x$ to $x + 1$).\n:::\n\n## Fit the model with brms\n\n``` r\nrt_bm <- brm(\n  rt ~ 1 + log_freq,\n  family = gaussian,\n  data = croat\n)\n```\n\n\n::: {.cell}\n\n:::\n\n\n## Model summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(rt_bm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: rt ~ 1 + log_freq \n   Data: croat (Number of observations: 2612) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept  1106.79     11.25  1084.44  1128.79 1.00     4140     2687\nlog_freq    -45.56      1.14   -47.81   -43.33 1.00     4163     2633\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma   104.06      1.45   101.28   107.02 1.00     4397     3032\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n## Regression coefficients: intercept\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Est.Error       Q2.5      Q97.5\nIntercept 1106.78704 11.249044 1084.43507 1128.78687\nlog_freq   -45.56409  1.142898  -47.81221  -43.33064\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Intercept `Intercept`\n\n-   `Estimate` = posterior mean: 1107 ms.\n\n-   `Est.Error` = posterior SD: 11 ms.\n\n-   `Q2.5 Q97.5` = posterior 95% CrI: \\[1084, 1129\\] ms.\n:::\n\n## Posterior distribution: intercept\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/rt-bm-int-dens-1.png){width=960}\n:::\n:::\n\n\n## Regression coefficients: slope\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Est.Error       Q2.5      Q97.5\nIntercept 1106.78704 11.249044 1084.43507 1128.78687\nlog_freq   -45.56409  1.142898  -47.81221  -43.33064\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Slope `log_freq`\n\n-   `Estimate` = posterior mean: -46 ms.\n\n-   `Est.Error` = posterior SD: 1 ms.\n\n-   `Q2.5 Q97.5` = posterior 95% CrI: \\[-48, -43\\] ms.\n:::\n\n## Posterior distribution: slope\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/rt-bm-slo-dens-1.png){width=960}\n:::\n:::\n\n\n## Posterior predictions\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-05_files/figure-revealjs/rt-bm-cond-1.png){width=960}\n:::\n:::\n\n\n## Word frequency and reaction times (bis)\n\n::: {.callout-tip appearance=\"simple\"}\n**What is the relationship between a word's lexical frequency and reaction times in a lexical decision task in Croatian?**\n:::\n\n. . .\n\n::: {.callout-note appearance=\"simple\"}\n-   When log-frequency is 0, the mean RTs are between 1084 and 1129 ms at 95% confidence.\n\n-   For each unit increase of log-frequency, the mean RTs decrease by 43-48 ms, at 95% confidence.\n:::\n\n## Be careful!\n\n::: callout-important\n### Correlation is NOT causation\n\n-   Correlation between two variables: they co-vary (when one changes, the other systematically changes too).\n\n-   Spurious correlations: two variables look correlated because of a confounder.\n:::\n\n. . .\n\n::: callout-note\n1.  Vocabulary for snow vs latitude\n    -   The farther north a community lives, the more words their language has for snow.\n    -   **Confounder**: subsistence ecology.\n2.  Number of plant names in a language vs. biodiversity of the region\n    -   Languages in biodiverse regions have more words for plants.\n    -   **Confounder**: cultural reliance on plants.\n3.  Metaphors involving animals vs. level of industrialization\n    1.  Less industrialized societies use more animal-based metaphors\n    2.  **Confounder**: daily exposure to animals.\n:::\n\n## Be careful!\n\n::: callout-tip\n### But it is if you use causal inference\n\n-   Correlation *can* be interpreted causally if you adopt a **causal inference** approach.\n\n-   We won't treat causal inference in this course due to time, but you can learn about it in McElreath's textbook *Statistical Rethinking*.\n:::\n",
    "supporting": [
      "week-05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}