---
title: "QML - Week 7"
subtitle: "Frequentist statistics and the Null Ritual"
author: "Stefano Coretta"
format: revealjs
bibliography: references.bib
---

## Statistical significance

::: {.callout-note appearance="simple"}
Suppose you have a treatment that you suspect may alter performance on a certain task. You compare the means of your control and experimental groups (say 20 subjects in each sample). Further, suppose a significance test indicates a significant difference, with a *p*-value of 0.01. Which of the following statements are FALSE?
:::

:::::: columns
:::: {.column width="70%"}
::: {style="font-size: 18px;"}
1.  You have absolutely disproved the null hypothesis (that is, there is no difference between the population means).

2.  You have found the probability of the null hypothesis being true.

3.  You have absolutely proved your experimental hypothesis (that there is a difference between the population means).

4.  You can deduce the probability of the experimental hypothesis being true.

5.  You know, if you decide to reject the null hypothesis, the probability that you are making the wrong decision.

6.  You have a reliable experimental ﬁnding in the sense that if, hypothetically, the experiment were repeated a great number of times, you would obtain a signiﬁcant result on 99% of occasions.
:::
::::

::: {.column width="30%"}
```{=html}
<iframe style="width:100%;max-width:360px;height:360px;"
                    src="https://stopwatch-app.com/widget/timer?theme=light&color=indigo&hrs=0&min=10&sec=0" 
                    frameborder="0"></iframe>
```
:::
::::::

## Which statements are false?

```{=html}
<iframe allowfullscreen frameborder="0" height="100%" mozallowfullscreen style="min-width: 500px; min-height: 355px" src="https://app.wooclap.com/events/EIZPEY/questions/68d4127b003fb9fde7a375d6" width="100%"></iframe>
```

## Statistical significance is not meaningful

::: {.callout-note appearance="simple"}
-   Simulate N observations from two populations that have very similar means. Their difference is not linguistically meaningful.

-   N is sample size: from 50 to 500.

-   For each N, simulate N observations 100 times (100 draws). For each draw get the *p*-value of the difference. So 100 p-values for each N.
:::

## Statistical significance is not meaningful

```{r}
#| label: sample-size
#| echo: false
#| message: false
#| fig-width: 7
#| fig-align: center

library(tidyverse)
theme_set(theme_light())

sample_sizes <- seq(25, 500, by = 25)
n_draws <- 100

simulate_ttest <- function(n) {
  set.seed(8723)
  tibble(
    draw = 1:n_draws,
    p_value = map_dbl(1:n_draws, ~ {
      group1 <- rnorm(n, mean = 0, sd = 1)
      group2 <- rnorm(n, mean = 0.3, sd = 1)
      t.test(group1, group2)$p.value
    })
  )
}

results <- map_dfr(
  sample_sizes,
  ~simulate_ttest(.x) |> mutate(sample_size = .x)
)

results |> 
  ggplot(aes(as.factor(sample_size*2), p_value)) +
  geom_hline(yintercept = 0.05, colour = "orangered4") +
  geom_point(alpha = 0.25) +
  scale_y_continuous(breaks = c(seq(0, 1, 0.25), 0.05)) +
  labs(
    x = "Sample size",
    y = "p-value"
  )
```

## Group activity

::::::: columns
::::: {.column width="70%"}
:::: {.callout-note appearance="simple"}
Focus on the results sections of these papers and discuss how they compare with one another.

::: {style="font-size: 15px;"}
-   [Evaluating the Relative Importance of Wordhood Cues Using Statistical Learning](https://doi.org/10.1111/cogs.13429).

-   [Brain boosters: How bilingualism and working memory enhance children’s comprehension of which-questions](https://doi.org/10.1177/02676583251348942).

-   [Notes on the length of vowels](https://doi.org/10.2307/452621).
:::

How are the statistical approaches different? Which papers focus more on general directional patterns vs more precise estimation? How are the results weighted and use as evidence?
::::
:::::

::: {.column width="30%"}
```{=html}
<iframe style="width:100%;max-width:360px;height:360px;"
                    src="https://stopwatch-app.com/widget/timer?theme=light&color=indigo&hrs=0&min=20&sec=0" 
                    frameborder="0"></iframe>
```
:::
:::::::
