---
title: "Workshop: Week 4"
format: html
---

::: callout-important
## Instructions

- Work on Task A as a group, guided by the group navigator, then work on one of the other two tasks.
  Feel free to work on the remaining task as well if you have time.

- Each of you should complete the exercises on your laptop, using the RStudio project you created for the course.
  This includes writing text and code in a **Quarto document** and executing the code.
  You should use Quarto documents (rather than scripts) from now on (in the workshops and at home).
:::

::: callout-note
## Task A: Albanian Voice Onset Time

- [Data docs](https://uoelel.github.io/qml-data/data/coretta2021/alb-vot.html).

- Read the `coretta2021/alb-vot.csv` data in R.

- Calculate the VOT based on the `release` and `voi_onset` columns.
  (VOT is the time lag between the voicing onset and the consonant release).

- Create a new column that specifies the voicing of the consonant (voiced or voiceless) based on the value in `label`.
  `ifelse()` or `case_when()` are useful.

- Get summary measures of VOT for voiceless and voiced consonants.
  Can the VOT differentiate between the two voicing categories?
:::

::: callout-note
## Task B: Albanian vowels

- [Data docs](https://uoelel.github.io/qml-data/data/coretta2021/alb_formants.html).

- Read the `coretta2021/alb_formants.rds` data in R.

- Create a scatter plot of F1 and F2, with points coloured by `vowel`.
  Are the vowels in the places you'd expect them to be?

- Now create another scatter plot with F1 and vowel duration.
  You need to calculate vowel duration first from `start` and `end`.
  Can you notice any patterns in the relationship between F1 and vowel duration?
:::

::: callout-note
## Task C: **'Everywhere here can say this'**

- [Data docs](https://uoelel.github.io/qml-data/data/sluckin2022/everywhere-loc.html).

- Read the `sluckin2022/everywhere-loc.csv` data in R.
  The data are acceptability judgements on the impersonal use of "everywhere", like in the sentence "Everywhere here can say this".

- The `Restrictor` column tells you if the sentence has a restrictor, like in "Everywhere *on the coast* eats fish and chips." vs no restrictor "Everywhere takes credit cards these days." The `Value` column gives you the acceptability rating from 1 to 7.

- Mutate the `Restrictor` column so that 0 = "no restrictor" and 1 = "restrictor".

- Mutate the `Value` column so that it is a character column (use `as.character()`).

- Create a filled stacked bar chart by `Restrictor` with fill by `Value` and panels by `Age`.
  Can you spot differences in rating across different age brackets?
:::
