---
title: "Workshop: Week 6"
format: html
---

::: callout-important
## Instructions

- Pick one of the following tasks and work as a group, guided by the group navigator.

- While this week focusses on regression models and the tasks below are for you to practice them, you should also get summary measures and plot the data, so that you familiarise yourself with the data sets and you keep practising skills learned in earlier weeks.

**When completing your chosen task, you are expected to:**

- Learn about the task data by reading the linked data docs.

- Use a Quarto document for your code and text.

- Read the data and familiarise yourself with it.
  As mentioned above, you should calculate summary measures and create plots of relevant variables (based on the given research question).

- Work out and discuss the mathematical formula of the regression model to fit to answer the research question.

- Fit the regression model.

- Discuss the summary, plot and calculate summaries of the posterior draws of the coefficients and expected values.

- Write a result paragraph where you report the model specification and the results.
:::

::: callout-note
## Task A: Massive Auditory Lexical Decision (MALD)

- [Data docs](https://uoelel.github.io/qml-data/data/tucker2019/mald_1_1.html).

- Data: `tucker2019/mald_1_1.rds`.

- Filter the data to include only real words.

- What is the relationship between reaction times (`RT`) and mean phoneme-level Levenshtein distance (`PhonLev`)?

  - You can check the publication linked on the [data documentation](https://uoelel.github.io/qml-data/data/tucker2019/mald_1_1.html) to learn about the mean phoneme-level Levenshtein distance.

- Why does `PhonLev` have the effect it has on reaction times?
:::

::: callout-note
## Task B: Korean voice quality

- [Data docs](https://uoelel.github.io/qml-data/data/winter2012/polite.html).

- Data: `winter2012/polite.csv`.

- Filter the data to include only female participants.

- Fit a regression model of mean f0 (`f0mn`) and mean harmonic-to-noise ratio (`HNRmn`, the higher the HNR, the more modal the voice is).
  What is the relationship between mean f0 and mean HNR in female Korean speakers?
:::

::: callout-note
## Task C: Reading fixation times (eye-tracking)

- [Data docs](https://uoelel.github.io/qml-data/data/berzak2025/fix-dur.html).

- Data: `berzak2025/fix-dur.csv`.

- What is the relationship between the current fixation duration and the length of the word being fixated?
:::
