---
title: "Workshop: Week 8"
format: html
---

::: callout-important
## Instructions

- Pick one of tasks A-C and work as a group, guided by the group navigator.
  After you have finished with your chosen task, complete task D.

- While this week focusses on Bernoulli and log-normal regression models and the tasks below are for you to practice them, you should also get summary measures and plot the data, so that you familiarise yourself with the data sets and you keep practising skills learned in earlier weeks.

**When completing your chosen task, you are expected to:**

- Learn about the task data by reading the linked data docs.

- Use a Quarto document for your code and text.

- Read the data and familiarise yourself with it.
  As mentioned above, you should calculate summary measures and create plots of relevant variables (based on the given research question).

- Work out and discuss the mathematical formula of the regression model to fit to answer the research question.

- Fit the regression model.

- Check the model diagnostics.

- Discuss the summary, plot and calculate summaries of the posterior draws of the coefficients and expected values.

- Write a result paragraph where you report the model specification and the results.
:::

## Bernoulli models (pick one task)

::: callout-note
## Task A: Scalar inferences and semantic distance

- [Data docs](https://uoelel.github.io/qml-data/data/pankratz2021/si.html).

- Data: `pankratz2021/si.csv.`

- Does the semantic distance (`semdist`) of the weak and strong adjective affect the probability of a scalar inference (`SI`)?

<!-- -->

- Discuss the results with your group (no need to write the discussion).
:::

::: callout-note
## Task B: Shallow Structure Hypothesis

- [Data docs](https://uoelel.github.io/qml-data/data/song2020/shallow.html).

- Data: `song2020/shallow.csv`.

- Filter the data so it contains only L2 data (`Group`) and critical trials (`Critical_Filler`).

- How does relation type of prime-target (`Relation_type`) affect accuracy (`ACC`) in L2 speakers of English?

- Discuss the results with your group (no need to write the discussion).
:::

::: callout-note
## Task C: Simulate data

- Imagine a study with one research question/hypothesis that requires a Bernoulli regression.

- Simulate Bernoulli data based on the study design.

- Fit a regression model to answer a question with the simulated data.

- Discuss the results with your group (no need to write the discussion).
:::

## Log-normal model

::: callout-note
## Task D: Vowel duration

- [Data docs](https://uoelel.github.io/qml-data/data/coretta2018a/ita_egg.html).

- Data: `coretta2018a/ita_egg.rda`.

- How does vowel duration (`v1_duration`) differ by vowel type (`vowel`)?

- Discuss the results with your group (no need to write the discussion).
:::
