---
title: "Equality, diversity and inclusiveness in quantitative linguistics"
author: "Stefano Coretta"
---

Equality, diversity and inclusiveness (EDI) is a very important concept of ethics related to research.

In the field of linguistics, EDI affects any study, whether quantitative, qualitative or formal. The prompts below touch upon some linguistic topics. Imagine you have to conduct a study to answer any of the questions in the prompts: think about how you would go about collecting quantitative data and how you could analyse it.

::: callout-note
#### Prompts

1. Research on speech production usually investigates sex, rather than gender. While fundamental frequency (f0) might be related to sex, less is known about its relation with gender, especially for non-binary folk and transgender people. Think about a study that addresses this gap.

2. The majority of knowledge in relation to syntax comes from colonising languages like English. Acceptability judgements are commonly employed in quantitative studies of syntax but they are less frequently employed in non-[WIERD](https://en.wikipedia.org/wiki/The_WEIRDest_People_in_the_World) contexts. How would you do about collecting and analysis acceptability ratings from minorities languages?

3. How would you investigate the effect of cultural background on the pragmatics of any specific language?
:::

