---
title: "What's next"
author: "Stefano Coretta"
---

We are approaching the end of the course. While I am sure everyone of you has learnt **a lot** in just 9 weeks, the truth is that, to become comfortable with quantitative data analysis and statistics it takes much much more than a single semester (especially if you want to become proficient in it, as in, not only be able to perform a few analysis as in a cookbook, but grow a understanding of the conceptual and methodological theory behind applied statistics).

If quantitative research is something you see yourself doing in the future (whether it's for academia or industry), you should factor in at least 5/6 years of learning to reach a working knowledge. For a deeper and advanced understanding, make that 10 years. (Think about it: you didn't learn linguistics in one semester before doing a dissertation...).

There are no specific prompts for this week's seminar. Rather, think about the type of research you might be doing for your dissertation, or research you are interested in, and ask us which further topics you might want to focus on in the future.

(For a more personalised suggestion, feel free to book office hours with Stefano!)

