---
title: "Catalogues and tips for R plots"
subtitle: "A list of plot clatalogues and tips"
format: 
  html:
    css: [webex.css]
    include-after-body: [webex.js]
date: 2024-10-23
---

```{r}
#| label: packages
#| echo: false
#| message: false

library(tidyverse)
library(webexercises)
```

::: callout-warning
## Prerequisites

- [Plotting basics](plotting-basics.qmd)

:::

## Data Visualisation

The book *Fundamentals of Data Visualisation* by Wilke is a good introduction to data visualisation principles. You can find the book online here: [Fundamentals of Data Visualisation](https://clauswilke.com/dataviz/).

You should also check [Level Up Your Labels: Tips and Tricks for Annotating Plots](https://www.cararthompson.com/talks/user2022/) and [Graphic design](https://rstudio-conf-2022.github.io/ggplot2-graphic-design/).

## Catalogues

A list of plot catalogues. If you want to get inspired, follow these links!

- [Directory of visualisations](https://clauswilke.com/dataviz/directory-of-visualizations.html)
- [Data viz catalogue](https://datavizcatalogue.com/index.html)
- [Data Viz project](https://datavizproject.com)
- [Top 50](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
- [Data Viz](https://datavizm20.classes.andrewheiss.com/)
- [Raincloud plots](https://wellcomeopenresearch.org/articles/4-63)
- [Upset graphs](https://upset.app)

## Colour

Colour tips and palettes:

- [ColorBrewer2](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3).
- [MetBrewer](https://github.com/BlakeRMills/MetBrewer)
- [Use colour wisely](https://albert-rapp.de/post/2022-02-19-ggplot2-color-tips-from-datawrapper/).
- [paleteer gallery](https://pmassicotte.github.io/paletteer_gallery/) and the [paleteer](https://emilhvitfeldt.github.io/paletteer/) package.
- [Carto colors](https://carto.com/carto-colors/)

## Specific recommendations

- [Same stats different data](https://www.research.autodesk.com/app/uploads/2023/03/same-stats-different-graphs.pdf_rec2hRjLLGgM7Cn2T.pdf).
- [Behind bars](https://stats.stackexchange.com/a/367889).
- [I stopped using box plots](https://nightingaledvs.com/ive-stopped-using-box-plots-should-you/).
- [Issues with error bars](https://www.data-to-viz.com/caveat/error_bar.html).
- [Visual Word Paradigm](https://link.springer.com/article/10.3758/s13423-022-02143-8).
- [Friends Don't Let Friends Make Bad Graphs](https://github.com/cxli233/FriendsDontLetFriends).

Some recommendations from me:

-   **Make sure you use the appropriate type of visualisation for different types of variables**. If the variable is continuous then you can use a continuous axis, but if they are discrete (like categories or scales), you should make sure the axis is discrete and not treated as numeric (for example, you can convert a column to factor if it's read as numeric). Some things that look numeric/continuous are in fact discrete, like scales or ratings.
-   **DO NOT USE BOX PLOTS**: they are REALLY bad for a bunch of reasons. For a visual example, see here: [https://www.autodesk.com/research/publications/same-stats-different-graphs](https://www.autodesk.com/research/publications/same-stats-different-graphs).
-   Good alternatives to box plots are strip charts and violin plots (with `geom_jitter()` and `geom_violin()`).
-   **ONLY USE BAR CHARTS FOR COUNTS**. If you are dealing with counts of stuff (money, words, gestures, phones, etc) then you can use bar charts. You will never need error bars in this case (if you feel that you could add error bars, probably you should not use bar charts). Use stacked bar charts to show proportions.
-   If you have collected counts from multiple participants (adults, children, learners, etc), then you can use a strip chart to show the counts or proportion of each participant as individual points on the graph. **DO NOT USE BAR CHARTS TO SHOW MEAN PROPORTIONS**, see [Accuracy and computing proportions](plot-advanced.qmd#sec-accuracy).
- Connected point plots also work with time series data when you want to show individual trajectories: [example](https://srcd.onlinelibrary.wiley.com/cms/asset/202b12cd-28b1-4d17-8853-ceb8e55b4b1c/cdev13406-fig-0001-m.jpg)
-   **Use colour wisely.** If you need more than 4/5 different colours then perhaps you might want to reconsider using colour at all. With a lot of colours you end up with very similar colours. Also, make sure the colours you pick are colour-blind safe ([https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3)).
-   You can create **interactive plots with plotly**: for example, [https://plotly.com/r/line-and-scatter/](https://plotly.com/r/line-and-scatter/) Even interactive 3D plots: [https://stefanocoretta.github.io/posts/2021-01-29-rgb-space/](https://stefanocoretta.github.io/posts/2021-01-29-rgb-space/). Do not make static 3D plots, they are difficult to read. See [Interactive plots](plot-plotly.qmd).
-   Density plots and histograms with rugs are useful to visualise a continuous variable. Rain-cloud plots too. [Examples](https://wellcomeopenresearch.org/articles/4-63)
-   **Make sure the plot is standalone**: anybody looking at it should understand what it is about without having to read your paper/dissertation. Make clever use of axes labels, titles, subtitles, legends and so on. Enhance you plot without making it crowded.
-   Check out this **YT video for some data viz principles**: [https://youtu.be/8y9AIe-tBh4](https://youtu.be/8y9AIe-tBh4)
-   Check out the intRo workshop slides for some other types of plots: [https://intro-rstats.github.io/intro-slides/](https://intro-rstats.github.io/intro-slides/) (more info on the workshop here [https://intro-rstats.github.io).](https://intro-rstats.github.io/)
-   **DO NOT USE BOX PLOTS AND USE BAR CHARTS FOR COUNTS AND RAW PROPORTIONS ONLY. (It goes without saying that you shall NEVER use a pie chart).**
