---
title: "Regression models: interactions"
description: "Add and interpret interactions in regression models"
author: "Stefano Coretta"
date: 2024-08-08
execute: 
  freeze: auto
format: 
  html:
    css: [webex.css]
    include-after-body: [webex.js]
    embed-resources: true 
---

```{r}
#| label: setup
#| include: false
library(webexercises)
library(tidyverse)
library(brms)
```

```{r}
mald <- readRDS("data/tucker2019/mald_1_1.rds")

mald <- mald |> 
  mutate(
    PhonLev_c = PhonLev - mean(PhonLev)
  )
```

```{r}
mald_rt_bm_noint <- brm(
  RT_log ~ 0 + IsWord + PhonLev_c,
  family = gaussian,
  data = mald,
  seed = 9284,
  cores = 4,
  file = "data/cache/mald_rt_bm_noint"
)
```

```{r}
conditional_effects(mald_rt_bm_noint, "PhonLev_c:IsWord")
```


```{r}
mald_rt_bm <- brm(
  RT_log ~ 0 + IsWord + IsWord:PhonLev_c,
  family = gaussian,
  data = mald,
  seed = 9284,
  cores = 4,
  file = "data/cache/mald_rt_bm"
)
```

```{r}
summary(mald_rt_bm, prob = 0.8)
```

```{r}
conditional_effects(mald_rt_bm, "PhonLev_c:IsWord")
```

```{r}
mald_rt_draws <- as_draws_df(mald_rt_bm)

mald_rt_draws
```

```{r}
mald_rt_preds_5 <- mald_rt_draws |> 
  mutate(
    word_5 = b_IsWordTRUE + (5 * `b_IsWordTRUE:PhonLev_c`),
    non_word_5 = b_IsWordFALSE + (5 * `b_IsWordFALSE:PhonLev_c`),
  )

mald_rt_preds_5 |> 
  select(word_5:non_word_5)
```

```{r}
mald_rt_preds_5 |> 
  mutate(
    word_nonword_5 = exp(non_word_5) - exp(word_5)
  ) |> 
  summarise(
    lo_80 = quantile2(word_nonword_5, 0.1),
    hi_80 = quantile2(word_nonword_5, 0.9),
  )
```

```{r}
library(ggdist)

mald_rt_preds_5 |> 
  mutate(
    word_nonword_5 = exp(non_word_5) - exp(word_5)
  ) |> 
  ggplot(aes(word_nonword_5)) +
  stat_halfeye()
```
