{
  "hash": "a425d14c423d2d72ea311cdba4e05585",
  "result": {
    "markdown": "---\ntitle: \"QML tutorial - Week 4\"\neditor: visual\nexecute: \n  freeze: auto\nformat: \n  html:\n    css: [webex.css]\n    include-after-body: [webex.js]\n    embed-resources: true \n---\n\n::: {.cell}\n\n:::\n\n\nLet's pick up from where we left off last week.\n\nIn week 3, you learnt how to use ggplot2 to create bar charts and how to create different panels. Bar charts are great for categorical data.\n\nThis week you will learn how to make density and violin plots, which work very well with numeric data in combination of categorical data (for example, when you want to show values of a numeric variable across different groups).\n\nThen, you will use the `brm()` function from the [brms](https://paul-buerkner.github.io/brms/) package to model continuous variables.\n\nBut first, let's read some data and transform it so that we can use it in the tutorial.\n\n## Mutating data\n\n### The `alb_vot` data\n\n::: callout-warning\n#### Important\n\nWhen working through these tutorials, always **make sure you are in the course RStudio Project** you just created.\n\nYou know you are in an RStudio Project because you can see the name of the Project in the top-right corner of RStudio, next to the light-blue cube icon.\n\nIf you see `Project (none)` in the top-right corner, that means **you are not** in an RStudio Project.\n\nTo make sure you are in the RStudio project, you can open the project by going to the project folder in File Explorer (Win) or Finder (macOS) and double click on the `.Rproj` file.\n:::\n\nLet's play around with the Albanian VOT data we used in class.\n\nThe data comes from the paper by Coretta and colleagues, 2022. *Northern Tosk Albanian*. DOI: [10.1017/S0025100322000044](https://doi.org/10.1017/S0025100322000044). This is an IPA Illustration of Northern Tosk Albanian. It contains data from voiceless and voiced consonants of Nothern Tosk Albanian, as uttered in a set of words by 5 speakers.\n\nTo download the file with the data right-click on the following link and download the file: [alb_vot.csv](../data/alb_vot.csv). (Note that tutorial files are also linked in [Course content](../content.qmd)). Remember to save the file in `data/` in the course project folder.\n\nCreate a new `.Rmd` file first, save it in `code/` and name it `tutorial-w04` (the extension `.Rmd` is added automatically!).\n\nI leave to you creating headings in your file as you please. Remember to to add `knitr::opts_knit$set(root.dir = here::here())` in the `setup` chunk and to attach the tidyverse.\n\nNow you can create a new code chunk and read the `alb_vot.csv` file in R. Remember how to do this?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot <- ...\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hint\n\nIt's one of the `read_*()` functions.\n:::\n\n\n::: {.cell}\n\n:::\n\n\nGreat!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"speaker\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"file\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"label\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"release\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"voi_onset\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"consonant\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"s01\",\"2\":\"001-cica\",\"3\":\"ts\",\"4\":\"1.6449206\",\"5\":\"1.74306122\",\"6\":\"ts\"},{\"1\":\"s01\",\"2\":\"002-bari\",\"3\":\"b\",\"4\":\"0.4556689\",\"5\":\"0.35190476\",\"6\":\"b\"},{\"1\":\"s01\",\"2\":\"004-gati\",\"3\":\"g\",\"4\":\"0.8180726\",\"5\":\"0.68893424\",\"6\":\"ɡ\"},{\"1\":\"s01\",\"2\":\"011-kati\",\"3\":\"k\",\"4\":\"0.7539456\",\"5\":\"0.78539683\",\"6\":\"k\"},{\"1\":\"s01\",\"2\":\"014-pata\",\"3\":\"p\",\"4\":\"0.7045125\",\"5\":\"0.71197279\",\"6\":\"p\"},{\"1\":\"s01\",\"2\":\"020-tapa\",\"3\":\"t\",\"4\":\"0.8247166\",\"5\":\"0.83272109\",\"6\":\"t\"},{\"1\":\"s01\",\"2\":\"022-data\",\"3\":\"d\",\"4\":\"0.8550794\",\"5\":\"0.76741497\",\"6\":\"d\"},{\"1\":\"s01\",\"2\":\"026-xixa\",\"3\":\"dz\",\"4\":\"0.7801134\",\"5\":\"0.67580499\",\"6\":\"dz\"},{\"1\":\"s01\",\"2\":\"027-5aji\",\"3\":\"tS\",\"4\":\"0.8429252\",\"5\":\"0.91736961\",\"6\":\"tʃ\"},{\"1\":\"s01\",\"2\":\"029-gjaku\",\"3\":\"J\",\"4\":\"0.9600907\",\"5\":\"0.86213152\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s01\",\"2\":\"030-qava\",\"3\":\"c\",\"4\":\"0.9275510\",\"5\":\"1.01764172\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s01\",\"2\":\"037-xhaja\",\"3\":\"dZ\",\"4\":\"0.7642630\",\"5\":\"0.66038549\",\"6\":\"dʒ\"},{\"1\":\"s01\",\"2\":\"042-cica\",\"3\":\"ts\",\"4\":\"3.9090476\",\"5\":\"3.99605442\",\"6\":\"ts\"},{\"1\":\"s01\",\"2\":\"043-bari\",\"3\":\"b\",\"4\":\"0.8066213\",\"5\":\"0.72201814\",\"6\":\"b\"},{\"1\":\"s01\",\"2\":\"045-gati\",\"3\":\"g\",\"4\":\"1.0112472\",\"5\":\"0.89997732\",\"6\":\"ɡ\"},{\"1\":\"s01\",\"2\":\"052-kati\",\"3\":\"k\",\"4\":\"0.7723129\",\"5\":\"0.80734694\",\"6\":\"k\"},{\"1\":\"s01\",\"2\":\"055-pata\",\"3\":\"p\",\"4\":\"0.8228798\",\"5\":\"0.83786848\",\"6\":\"p\"},{\"1\":\"s01\",\"2\":\"061-tapa\",\"3\":\"t\",\"4\":\"0.9443311\",\"5\":\"0.95294785\",\"6\":\"t\"},{\"1\":\"s01\",\"2\":\"063-data\",\"3\":\"d\",\"4\":\"0.9553061\",\"5\":\"0.83083900\",\"6\":\"d\"},{\"1\":\"s01\",\"2\":\"068-xixa\",\"3\":\"dz\",\"4\":\"0.7226304\",\"5\":\"0.62195011\",\"6\":\"dz\"},{\"1\":\"s01\",\"2\":\"069-5aji\",\"3\":\"tS\",\"4\":\"0.6364399\",\"5\":\"0.69759637\",\"6\":\"tʃ\"},{\"1\":\"s01\",\"2\":\"071-gjaku\",\"3\":\"J\",\"4\":\"0.8603401\",\"5\":\"0.77562358\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s01\",\"2\":\"072-qava\",\"3\":\"c\",\"4\":\"0.7148526\",\"5\":\"0.78031746\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s01\",\"2\":\"079-xhaja\",\"3\":\"dZ\",\"4\":\"0.9422676\",\"5\":\"0.83759637\",\"6\":\"dʒ\"},{\"1\":\"s01\",\"2\":\"083-cica\",\"3\":\"ts\",\"4\":\"2.3342404\",\"5\":\"2.42308390\",\"6\":\"ts\"},{\"1\":\"s01\",\"2\":\"084-bari\",\"3\":\"b\",\"4\":\"0.7083900\",\"5\":\"0.60142857\",\"6\":\"b\"},{\"1\":\"s01\",\"2\":\"086-gati\",\"3\":\"g\",\"4\":\"0.9669841\",\"5\":\"0.88643991\",\"6\":\"ɡ\"},{\"1\":\"s01\",\"2\":\"093-kati\",\"3\":\"k\",\"4\":\"0.9079819\",\"5\":\"0.94607710\",\"6\":\"k\"},{\"1\":\"s01\",\"2\":\"096-pata\",\"3\":\"p\",\"4\":\"1.0979365\",\"5\":\"1.10417234\",\"6\":\"p\"},{\"1\":\"s01\",\"2\":\"102-tapa\",\"3\":\"t\",\"4\":\"0.9509524\",\"5\":\"0.96401361\",\"6\":\"t\"},{\"1\":\"s01\",\"2\":\"104-data\",\"3\":\"d\",\"4\":\"1.1672562\",\"5\":\"1.04916100\",\"6\":\"d\"},{\"1\":\"s01\",\"2\":\"109-xixa\",\"3\":\"dz\",\"4\":\"0.8648073\",\"5\":\"0.92918367\",\"6\":\"dz\"},{\"1\":\"s01\",\"2\":\"110-5aji\",\"3\":\"tS\",\"4\":\"0.8689116\",\"5\":\"0.94675737\",\"6\":\"tʃ\"},{\"1\":\"s01\",\"2\":\"112-gjaku\",\"3\":\"J\",\"4\":\"0.8815646\",\"5\":\"0.75804989\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s01\",\"2\":\"113-qava\",\"3\":\"c\",\"4\":\"0.9263039\",\"5\":\"1.01693878\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s01\",\"2\":\"120-xhaja\",\"3\":\"dZ\",\"4\":\"0.7680726\",\"5\":\"0.65242630\",\"6\":\"dʒ\"},{\"1\":\"s02\",\"2\":\"001-5aji\",\"3\":\"tS\",\"4\":\"2.1101361\",\"5\":\"2.21827664\",\"6\":\"tʃ\"},{\"1\":\"s02\",\"2\":\"003-xhaja\",\"3\":\"dZ\",\"4\":\"0.7507483\",\"5\":\"0.66766440\",\"6\":\"dʒ\"},{\"1\":\"s02\",\"2\":\"008-data\",\"3\":\"d\",\"4\":\"0.6731746\",\"5\":\"0.55299320\",\"6\":\"d\"},{\"1\":\"s02\",\"2\":\"011-tapa\",\"3\":\"t\",\"4\":\"0.7521315\",\"5\":\"0.76603175\",\"6\":\"t\"},{\"1\":\"s02\",\"2\":\"017-cica\",\"3\":\"ts\",\"4\":\"0.5758957\",\"5\":\"0.65820862\",\"6\":\"ts\"},{\"1\":\"s02\",\"2\":\"020-kati\",\"3\":\"k\",\"4\":\"0.6957823\",\"5\":\"0.75065760\",\"6\":\"k\"},{\"1\":\"s02\",\"2\":\"023-gjaku\",\"3\":\"J\",\"4\":\"0.7116780\",\"5\":\"0.60959184\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s02\",\"2\":\"024-qava\",\"3\":\"c\",\"4\":\"0.5778458\",\"5\":\"0.70424036\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s02\",\"2\":\"031-gati\",\"3\":\"g\",\"4\":\"0.6533560\",\"5\":\"0.54811791\",\"6\":\"ɡ\"},{\"1\":\"s02\",\"2\":\"034-pata\",\"3\":\"p\",\"4\":\"0.7236508\",\"5\":\"0.73471655\",\"6\":\"p\"},{\"1\":\"s02\",\"2\":\"035-xixa\",\"3\":\"dz\",\"4\":\"0.6855556\",\"5\":\"0.58471655\",\"6\":\"dz\"},{\"1\":\"s02\",\"2\":\"039-bari\",\"3\":\"b\",\"4\":\"0.7480272\",\"5\":\"0.63344671\",\"6\":\"b\"},{\"1\":\"s02\",\"2\":\"042-5aji\",\"3\":\"tS\",\"4\":\"2.2436961\",\"5\":\"2.33671202\",\"6\":\"tʃ\"},{\"1\":\"s02\",\"2\":\"044-xhaja\",\"3\":\"dZ\",\"4\":\"0.6359637\",\"5\":\"0.53995465\",\"6\":\"dʒ\"},{\"1\":\"s02\",\"2\":\"049-data\",\"3\":\"d\",\"4\":\"0.6419501\",\"5\":\"0.54233560\",\"6\":\"d\"},{\"1\":\"s02\",\"2\":\"052-tapa\",\"3\":\"t\",\"4\":\"0.7002268\",\"5\":\"0.71117914\",\"6\":\"t\"},{\"1\":\"s02\",\"2\":\"058-cica\",\"3\":\"ts\",\"4\":\"0.6390249\",\"5\":\"0.70532880\",\"6\":\"ts\"},{\"1\":\"s02\",\"2\":\"061-kati\",\"3\":\"k\",\"4\":\"0.6082540\",\"5\":\"0.65233560\",\"6\":\"k\"},{\"1\":\"s02\",\"2\":\"064-gjaku\",\"3\":\"J\",\"4\":\"0.7730612\",\"5\":\"0.62294785\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s02\",\"2\":\"065-qava\",\"3\":\"c\",\"4\":\"0.6428798\",\"5\":\"0.72315193\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s02\",\"2\":\"072-gati\",\"3\":\"g\",\"4\":\"0.6448980\",\"5\":\"0.51913832\",\"6\":\"ɡ\"},{\"1\":\"s02\",\"2\":\"075-pata\",\"3\":\"p\",\"4\":\"0.7039683\",\"5\":\"0.71566893\",\"6\":\"p\"},{\"1\":\"s02\",\"2\":\"076-xixa\",\"3\":\"dz\",\"4\":\"0.6471882\",\"5\":\"0.52097506\",\"6\":\"dz\"},{\"1\":\"s02\",\"2\":\"080-bari\",\"3\":\"b\",\"4\":\"0.7995011\",\"5\":\"0.65680272\",\"6\":\"b\"},{\"1\":\"s02\",\"2\":\"083-5aji\",\"3\":\"tS\",\"4\":\"1.5513605\",\"5\":\"1.62927438\",\"6\":\"tʃ\"},{\"1\":\"s02\",\"2\":\"085-xhaja\",\"3\":\"dZ\",\"4\":\"0.6534694\",\"5\":\"0.56954649\",\"6\":\"dʒ\"},{\"1\":\"s02\",\"2\":\"090-data\",\"3\":\"d\",\"4\":\"0.6147619\",\"5\":\"0.50439909\",\"6\":\"d\"},{\"1\":\"s02\",\"2\":\"093-tapa\",\"3\":\"t\",\"4\":\"0.8278685\",\"5\":\"0.83839002\",\"6\":\"t\"},{\"1\":\"s02\",\"2\":\"099-cica\",\"3\":\"ts\",\"4\":\"0.6250794\",\"5\":\"0.70866213\",\"6\":\"ts\"},{\"1\":\"s02\",\"2\":\"102-kati\",\"3\":\"k\",\"4\":\"0.7340816\",\"5\":\"0.78251701\",\"6\":\"k\"},{\"1\":\"s02\",\"2\":\"105-gjaku\",\"3\":\"J\",\"4\":\"0.7736961\",\"5\":\"0.67775510\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s02\",\"2\":\"106-qava\",\"3\":\"c\",\"4\":\"0.6063039\",\"5\":\"0.73934240\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s02\",\"2\":\"113-gati\",\"3\":\"g\",\"4\":\"0.6989116\",\"5\":\"0.59117914\",\"6\":\"ɡ\"},{\"1\":\"s02\",\"2\":\"116-pata\",\"3\":\"p\",\"4\":\"0.8964626\",\"5\":\"0.90854875\",\"6\":\"p\"},{\"1\":\"s02\",\"2\":\"117-xixa\",\"3\":\"dz\",\"4\":\"0.6820862\",\"5\":\"0.57575964\",\"6\":\"dz\"},{\"1\":\"s02\",\"2\":\"121-bari\",\"3\":\"b\",\"4\":\"0.7731066\",\"5\":\"0.60095238\",\"6\":\"b\"},{\"1\":\"s04\",\"2\":\"001-data\",\"3\":\"d\",\"4\":\"0.8127891\",\"5\":\"0.68959184\",\"6\":\"d\"},{\"1\":\"s04\",\"2\":\"002-gjaku\",\"3\":\"J\",\"4\":\"0.7213152\",\"5\":\"0.66208617\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s04\",\"2\":\"005-xhaja\",\"3\":\"dZ\",\"4\":\"0.6819955\",\"5\":\"0.59324263\",\"6\":\"dʒ\"},{\"1\":\"s04\",\"2\":\"010-tapa\",\"3\":\"t\",\"4\":\"0.5601361\",\"5\":\"0.57002268\",\"6\":\"t\"},{\"1\":\"s04\",\"2\":\"011-xixa\",\"3\":\"dz\",\"4\":\"0.6019501\",\"5\":\"0.55632653\",\"6\":\"dz\"},{\"1\":\"s04\",\"2\":\"014-cica\",\"3\":\"ts\",\"4\":\"0.6415420\",\"5\":\"0.73834467\",\"6\":\"ts\"},{\"1\":\"s04\",\"2\":\"018-pata\",\"3\":\"p\",\"4\":\"0.5024717\",\"5\":\"0.50954649\",\"6\":\"p\"},{\"1\":\"s04\",\"2\":\"020-5aji\",\"3\":\"tS\",\"4\":\"0.6264853\",\"5\":\"0.72392290\",\"6\":\"tʃ\"},{\"1\":\"s04\",\"2\":\"026-bari\",\"3\":\"b\",\"4\":\"0.6126077\",\"5\":\"0.51478458\",\"6\":\"b\"},{\"1\":\"s04\",\"2\":\"030-gati\",\"3\":\"g\",\"4\":\"0.6453968\",\"5\":\"0.57088435\",\"6\":\"ɡ\"},{\"1\":\"s04\",\"2\":\"036-kati\",\"3\":\"k\",\"4\":\"0.6048299\",\"5\":\"0.64065760\",\"6\":\"k\"},{\"1\":\"s04\",\"2\":\"038-qava\",\"3\":\"c\",\"4\":\"0.5175057\",\"5\":\"0.63625850\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s04\",\"2\":\"043-data\",\"3\":\"d\",\"4\":\"7.9499773\",\"5\":\"7.80877551\",\"6\":\"d\"},{\"1\":\"s04\",\"2\":\"044-gjaku\",\"3\":\"J\",\"4\":\"0.4180045\",\"5\":\"0.34226757\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s04\",\"2\":\"047-xhaja\",\"3\":\"dZ\",\"4\":\"0.4984127\",\"5\":\"0.42634921\",\"6\":\"dʒ\"},{\"1\":\"s04\",\"2\":\"053-tapa\",\"3\":\"t\",\"4\":\"0.5162585\",\"5\":\"0.52507937\",\"6\":\"t\"},{\"1\":\"s04\",\"2\":\"054-xixa\",\"3\":\"dz\",\"4\":\"0.5465306\",\"5\":\"0.43589569\",\"6\":\"dz\"},{\"1\":\"s04\",\"2\":\"057-cica\",\"3\":\"ts\",\"4\":\"0.4720181\",\"5\":\"0.57514739\",\"6\":\"ts\"},{\"1\":\"s04\",\"2\":\"061-pata\",\"3\":\"p\",\"4\":\"0.5928345\",\"5\":\"0.60961451\",\"6\":\"p\"},{\"1\":\"s04\",\"2\":\"063-5aji\",\"3\":\"tS\",\"4\":\"0.5360998\",\"5\":\"0.62385488\",\"6\":\"tʃ\"},{\"1\":\"s04\",\"2\":\"069-bari\",\"3\":\"b\",\"4\":\"0.5658503\",\"5\":\"0.46138322\",\"6\":\"b\"},{\"1\":\"s04\",\"2\":\"073-gati\",\"3\":\"g\",\"4\":\"0.5610204\",\"5\":\"0.46482993\",\"6\":\"ɡ\"},{\"1\":\"s04\",\"2\":\"080-kati\",\"3\":\"k\",\"4\":\"0.5037188\",\"5\":\"0.56458050\",\"6\":\"k\"},{\"1\":\"s04\",\"2\":\"082-qava\",\"3\":\"c\",\"4\":\"0.5163265\",\"5\":\"0.66410431\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s04\",\"2\":\"085-data\",\"3\":\"d\",\"4\":\"3.6822676\",\"5\":\"3.54609977\",\"6\":\"d\"},{\"1\":\"s04\",\"2\":\"086-gjaku\",\"3\":\"J\",\"4\":\"0.5182540\",\"5\":\"0.42195011\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s04\",\"2\":\"089-xhaja\",\"3\":\"dZ\",\"4\":\"0.6464853\",\"5\":\"0.57827664\",\"6\":\"dʒ\"},{\"1\":\"s04\",\"2\":\"095-tapa\",\"3\":\"t\",\"4\":\"0.8013605\",\"5\":\"0.81512472\",\"6\":\"t\"},{\"1\":\"s04\",\"2\":\"096-xixa\",\"3\":\"dz\",\"4\":\"0.6068481\",\"5\":\"0.50766440\",\"6\":\"dz\"},{\"1\":\"s04\",\"2\":\"099-cica\",\"3\":\"ts\",\"4\":\"0.4767800\",\"5\":\"0.57192744\",\"6\":\"ts\"},{\"1\":\"s04\",\"2\":\"103-pata\",\"3\":\"p\",\"4\":\"0.7218594\",\"5\":\"0.75058957\",\"6\":\"p\"},{\"1\":\"s04\",\"2\":\"105-5aji\",\"3\":\"tS\",\"4\":\"0.7132880\",\"5\":\"0.80709751\",\"6\":\"tʃ\"},{\"1\":\"s04\",\"2\":\"110-bari\",\"3\":\"b\",\"4\":\"0.5357823\",\"5\":\"0.42814059\",\"6\":\"b\"},{\"1\":\"s04\",\"2\":\"114-gati\",\"3\":\"g\",\"4\":\"0.5497506\",\"5\":\"0.48755102\",\"6\":\"ɡ\"},{\"1\":\"s04\",\"2\":\"122-kati\",\"3\":\"k\",\"4\":\"0.6009070\",\"5\":\"0.65240363\",\"6\":\"k\"},{\"1\":\"s04\",\"2\":\"124-qava\",\"3\":\"c\",\"4\":\"0.5635147\",\"5\":\"0.67070295\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s05\",\"2\":\"003-qava\",\"3\":\"c\",\"4\":\"0.2115873\",\"5\":\"0.35746032\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s05\",\"2\":\"013-data\",\"3\":\"d\",\"4\":\"0.2444671\",\"5\":\"0.08582766\",\"6\":\"d\"},{\"1\":\"s05\",\"2\":\"014-xixa\",\"3\":\"dz\",\"4\":\"0.2067120\",\"5\":\"0.07866213\",\"6\":\"dz\"},{\"1\":\"s05\",\"2\":\"016-kati\",\"3\":\"k\",\"4\":\"0.1117007\",\"5\":\"0.22272109\",\"6\":\"k\"},{\"1\":\"s05\",\"2\":\"018-pata\",\"3\":\"p\",\"4\":\"0.2732653\",\"5\":\"0.28743764\",\"6\":\"p\"},{\"1\":\"s05\",\"2\":\"020-xhaja\",\"3\":\"dZ\",\"4\":\"0.3634014\",\"5\":\"0.27643991\",\"6\":\"dʒ\"},{\"1\":\"s05\",\"2\":\"022-5aji\",\"3\":\"tS\",\"4\":\"0.3500680\",\"5\":\"0.46403628\",\"6\":\"tʃ\"},{\"1\":\"s05\",\"2\":\"024-gjaku\",\"3\":\"J\",\"4\":\"0.3020181\",\"5\":\"0.22541950\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s05\",\"2\":\"030-tapa\",\"3\":\"t\",\"4\":\"0.2062132\",\"5\":\"0.23197279\",\"6\":\"t\"},{\"1\":\"s05\",\"2\":\"032-gati\",\"3\":\"g\",\"4\":\"0.2538549\",\"5\":\"0.12952381\",\"6\":\"ɡ\"},{\"1\":\"s05\",\"2\":\"036-bari\",\"3\":\"b\",\"4\":\"0.3567120\",\"5\":\"0.25081633\",\"6\":\"b\"},{\"1\":\"s05\",\"2\":\"039-cica\",\"3\":\"ts\",\"4\":\"0.2292063\",\"5\":\"0.32800454\",\"6\":\"ts\"},{\"1\":\"s05\",\"2\":\"044-qava\",\"3\":\"c\",\"4\":\"0.3180952\",\"5\":\"0.45181406\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s05\",\"2\":\"054-data\",\"3\":\"d\",\"4\":\"0.4672336\",\"5\":\"0.33997732\",\"6\":\"d\"},{\"1\":\"s05\",\"2\":\"055-xixa\",\"3\":\"dz\",\"4\":\"0.4258277\",\"5\":\"0.33467120\",\"6\":\"dz\"},{\"1\":\"s05\",\"2\":\"057-kati\",\"3\":\"k\",\"4\":\"0.4306122\",\"5\":\"0.52038549\",\"6\":\"k\"},{\"1\":\"s05\",\"2\":\"059-pata\",\"3\":\"p\",\"4\":\"0.3743311\",\"5\":\"0.39632653\",\"6\":\"p\"},{\"1\":\"s05\",\"2\":\"061-xhaja\",\"3\":\"dZ\",\"4\":\"0.4382766\",\"5\":\"0.25820862\",\"6\":\"dʒ\"},{\"1\":\"s05\",\"2\":\"063-5aji\",\"3\":\"tS\",\"4\":\"0.4538549\",\"5\":\"0.59439909\",\"6\":\"tʃ\"},{\"1\":\"s05\",\"2\":\"065-gjaku\",\"3\":\"J\",\"4\":\"0.3634014\",\"5\":\"0.26539683\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s05\",\"2\":\"071-tapa\",\"3\":\"t\",\"4\":\"0.3966667\",\"5\":\"0.41868481\",\"6\":\"t\"},{\"1\":\"s05\",\"2\":\"073-gati\",\"3\":\"g\",\"4\":\"0.5317914\",\"5\":\"0.40521542\",\"6\":\"ɡ\"},{\"1\":\"s05\",\"2\":\"078-bari\",\"3\":\"b\",\"4\":\"0.3877098\",\"5\":\"0.26170068\",\"6\":\"b\"},{\"1\":\"s05\",\"2\":\"081-cica\",\"3\":\"ts\",\"4\":\"0.3556916\",\"5\":\"0.44730159\",\"6\":\"ts\"},{\"1\":\"s05\",\"2\":\"086-qava\",\"3\":\"c\",\"4\":\"0.2789116\",\"5\":\"0.40918367\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s05\",\"2\":\"096-data\",\"3\":\"d\",\"4\":\"0.4184807\",\"5\":\"0.30385488\",\"6\":\"d\"},{\"1\":\"s05\",\"2\":\"097-xixa\",\"3\":\"dz\",\"4\":\"0.3665079\",\"5\":\"0.26616780\",\"6\":\"dz\"},{\"1\":\"s05\",\"2\":\"099-kati\",\"3\":\"k\",\"4\":\"0.3512925\",\"5\":\"0.45718821\",\"6\":\"k\"},{\"1\":\"s05\",\"2\":\"101-pata\",\"3\":\"p\",\"4\":\"0.3839456\",\"5\":\"0.40396825\",\"6\":\"p\"},{\"1\":\"s05\",\"2\":\"103-xhaja\",\"3\":\"dZ\",\"4\":\"0.4359637\",\"5\":\"0.30412698\",\"6\":\"dʒ\"},{\"1\":\"s05\",\"2\":\"105-5aji\",\"3\":\"tS\",\"4\":\"0.3382766\",\"5\":\"0.49267574\",\"6\":\"tʃ\"},{\"1\":\"s05\",\"2\":\"107-gjaku\",\"3\":\"J\",\"4\":\"0.3573243\",\"5\":\"0.25947846\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s05\",\"2\":\"113-tapa\",\"3\":\"t\",\"4\":\"0.2995011\",\"5\":\"0.34687075\",\"6\":\"t\"},{\"1\":\"s05\",\"2\":\"115-gati\",\"3\":\"g\",\"4\":\"0.3017234\",\"5\":\"0.15287982\",\"6\":\"ɡ\"},{\"1\":\"s05\",\"2\":\"120-bari\",\"3\":\"b\",\"4\":\"0.2897279\",\"5\":\"0.16292517\",\"6\":\"b\"},{\"1\":\"s05\",\"2\":\"123-cica\",\"3\":\"ts\",\"4\":\"0.2833333\",\"5\":\"0.35691610\",\"6\":\"ts\"},{\"1\":\"s06\",\"2\":\"003-xhaja\",\"3\":\"dZ\",\"4\":\"0.5511791\",\"5\":\"0.45562358\",\"6\":\"dʒ\"},{\"1\":\"s06\",\"2\":\"004-xixa\",\"3\":\"dz\",\"4\":\"0.5296825\",\"5\":\"0.44408163\",\"6\":\"dz\"},{\"1\":\"s06\",\"2\":\"005-gjaku\",\"3\":\"J\",\"4\":\"0.4929478\",\"5\":\"0.38897959\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s06\",\"2\":\"010-data\",\"3\":\"d\",\"4\":\"0.4885488\",\"5\":\"0.38759637\",\"6\":\"d\"},{\"1\":\"s06\",\"2\":\"020-bari\",\"3\":\"b\",\"4\":\"0.5565533\",\"5\":\"0.47530612\",\"6\":\"b\"},{\"1\":\"s06\",\"2\":\"021-5aji\",\"3\":\"tS\",\"4\":\"0.5247846\",\"5\":\"0.60034014\",\"6\":\"tʃ\"},{\"1\":\"s06\",\"2\":\"022-gati\",\"3\":\"g\",\"4\":\"0.7220862\",\"5\":\"0.61886621\",\"6\":\"ɡ\"},{\"1\":\"s06\",\"2\":\"024-kati\",\"3\":\"k\",\"4\":\"0.5097279\",\"5\":\"0.54099773\",\"6\":\"k\"},{\"1\":\"s06\",\"2\":\"025-cica\",\"3\":\"ts\",\"4\":\"0.4403628\",\"5\":\"0.51873016\",\"6\":\"ts\"},{\"1\":\"s06\",\"2\":\"030-pata\",\"3\":\"p\",\"4\":\"0.4586848\",\"5\":\"0.47328798\",\"6\":\"p\"},{\"1\":\"s06\",\"2\":\"032-tapa\",\"3\":\"t\",\"4\":\"0.5454875\",\"5\":\"0.55780045\",\"6\":\"t\"},{\"1\":\"s06\",\"2\":\"033-qava\",\"3\":\"c\",\"4\":\"0.5471655\",\"5\":\"0.60961451\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s06\",\"2\":\"045-xhaja\",\"3\":\"dZ\",\"4\":\"0.4974150\",\"5\":\"0.40448980\",\"6\":\"dʒ\"},{\"1\":\"s06\",\"2\":\"046-xixa\",\"3\":\"dz\",\"4\":\"0.4966893\",\"5\":\"0.39643991\",\"6\":\"dz\"},{\"1\":\"s06\",\"2\":\"047-gjaku\",\"3\":\"J\",\"4\":\"0.7109977\",\"5\":\"0.62521542\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s06\",\"2\":\"052-data\",\"3\":\"d\",\"4\":\"0.5193878\",\"5\":\"0.41403628\",\"6\":\"d\"},{\"1\":\"s06\",\"2\":\"062-bari\",\"3\":\"b\",\"4\":\"0.6053288\",\"5\":\"0.52253968\",\"6\":\"b\"},{\"1\":\"s06\",\"2\":\"063-5aji\",\"3\":\"tS\",\"4\":\"0.5797732\",\"5\":\"0.65433107\",\"6\":\"tʃ\"},{\"1\":\"s06\",\"2\":\"064-gati\",\"3\":\"g\",\"4\":\"0.4695918\",\"5\":\"0.38231293\",\"6\":\"ɡ\"},{\"1\":\"s06\",\"2\":\"066-kati\",\"3\":\"k\",\"4\":\"0.4571429\",\"5\":\"0.49879819\",\"6\":\"k\"},{\"1\":\"s06\",\"2\":\"067-cica\",\"3\":\"ts\",\"4\":\"0.5683900\",\"5\":\"0.62965986\",\"6\":\"ts\"},{\"1\":\"s06\",\"2\":\"072-pata\",\"3\":\"p\",\"4\":\"0.4290476\",\"5\":\"0.44095238\",\"6\":\"p\"},{\"1\":\"s06\",\"2\":\"074-tapa\",\"3\":\"t\",\"4\":\"0.5694785\",\"5\":\"0.58321995\",\"6\":\"t\"},{\"1\":\"s06\",\"2\":\"075-qava\",\"3\":\"c\",\"4\":\"0.6925624\",\"5\":\"0.75913832\",\"6\":\"t̻ʃ̻\"},{\"1\":\"s06\",\"2\":\"087-xhaja\",\"3\":\"dZ\",\"4\":\"0.4139683\",\"5\":\"0.32009070\",\"6\":\"dʒ\"},{\"1\":\"s06\",\"2\":\"088-xixa\",\"3\":\"dz\",\"4\":\"0.5272789\",\"5\":\"0.42698413\",\"6\":\"dz\"},{\"1\":\"s06\",\"2\":\"089-gjaku\",\"3\":\"J\",\"4\":\"0.5707029\",\"5\":\"0.49818594\",\"6\":\"d̻ʒ̻\"},{\"1\":\"s06\",\"2\":\"094-data\",\"3\":\"d\",\"4\":\"0.5653515\",\"5\":\"0.47476190\",\"6\":\"d\"},{\"1\":\"s06\",\"2\":\"104-bari\",\"3\":\"b\",\"4\":\"0.4743311\",\"5\":\"0.41038549\",\"6\":\"b\"},{\"1\":\"s06\",\"2\":\"105-5aji\",\"3\":\"tS\",\"4\":\"1.6635601\",\"5\":\"1.72605442\",\"6\":\"tʃ\"},{\"1\":\"s06\",\"2\":\"106-gati\",\"3\":\"g\",\"4\":\"0.4508390\",\"5\":\"0.34678005\",\"6\":\"ɡ\"},{\"1\":\"s06\",\"2\":\"108-kati\",\"3\":\"k\",\"4\":\"0.4065306\",\"5\":\"0.44709751\",\"6\":\"k\"},{\"1\":\"s06\",\"2\":\"109-cica\",\"3\":\"ts\",\"4\":\"0.5708844\",\"5\":\"0.65673469\",\"6\":\"ts\"},{\"1\":\"s06\",\"2\":\"114-pata\",\"3\":\"p\",\"4\":\"0.3619048\",\"5\":\"0.37580499\",\"6\":\"p\"},{\"1\":\"s06\",\"2\":\"116-tapa\",\"3\":\"t\",\"4\":\"0.4992517\",\"5\":\"0.51204082\",\"6\":\"t\"},{\"1\":\"s06\",\"2\":\"117-qava\",\"3\":\"c\",\"4\":\"0.8373016\",\"5\":\"0.89791383\",\"6\":\"t̻ʃ̻\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe data frame has the following columns:\n\n-   `speaker`: the speaker ID.\n-   `file`: the sound file the measurements are take from.\n-   `label`: the label in the interval the measurements are taken from.\n-   `release`: the time of the consonant's closure release from the beginning of the sound file in seconds.\n-   `voi_onset`: the onset of voicing of the vowel following the target consonant from the beginning of the sound file in seconds.\n-   `consonant`: the IPA transcription of the target consonant.\n\nNow we need to create a new column with the Voice Onset Time (`vot`) values. Note that VOT is simply the difference between the onset of voicing (`voi_onset`) and the time of release (`release`). We will do this in the next section.\n\n### Create a new column\n\nTo change or create columns, we can use the `mutate()` function from the [dplyr](https://dplyr.tidyverse.org) package. This is another tidyverse package, and it's attached when you attach the tidyverse. The `summarise()` and `count()` functions you used in Week 2 are from this same package.\n\nLet's calculate VOT now.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot <- alb_vot %>%\n  mutate(\n    vot = voi_onset - release\n  )\n```\n:::\n\n\nSince we are mutating `alb_vot`, we need to assign (`<-`) the output of `mutate()` back into `alb_vot`. Check the `alb_vot` data frame now to view the newly created column `vot` (to view the data frame, click on `alb_vot` in the Environment tab, in the top-right panel of Rstudio).\n\nWell done!\n\n::: callout-warning\nNote that the following code, without the pipe, gives you the same result.\n\n``` r\nalb_vot <- mutate(alb_vot, vot = voi_onset - release)\n```\n:::\n\nNormally, VOT is measured in milliseconds (ms), but the `vot` column is now in seconds (because `release` and `voi_onset` are in seconds).\n\nLet's change this. We can overwrite the `vot` column like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot <- alb_vot %>%\n  mutate(\n    # Multiply by 1000 to get ms from s\n    vot = (voi_onset - release) * 1000\n  )\n```\n:::\n\n\nCheck `alb_vot` now to see that it worked.\n\n::: callout-tip\n#### Mutate\n\nThe function `mutate()` allows you to create new columns or to change existing ones.\n:::\n\n## Density plots\n\n::: callout-tip\n#### Density plots\n\n**Density plots** show the distribution (i.e. the probability density) of the values of a continuous variable**.**\n\nThey are created with `geom_density()`.\n:::\n\nVOT is a numeric continuous variable so density plots are appropriate.\n\nTo plot the probability density of a continuous variable, you can use the `density` geometry. Remember, all geometry functions start with `geom_`.\n\nFill in the ... in the following code to create a density plot of VOT values in `alb_vot`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(x = vot)) +\n  ...\n```\n:::\n\n\nNote that to create a density plot, you only need to specify the `x`-axis. The `y`-axis is the probability density, which is automatically calculated (a bit like counts in bar charts, remember?).\n\n### Make things cosy with a rug\n\nThe density line shows you a smoothed representation of the data distribution over the VOT values, but you might also want to see the raw data.\n\nYou can do so by adding the `rug` geometry. Go ahead and add a rug...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(vot)) +\n  geom_density() +\n  ...\n```\n:::\n\n\nYou should get the following:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](tutorial-w04_files/figure-html/vot-dens-rug-1.png){width=672}\n:::\n:::\n\n\nNice huh?\n\n::: callout-tip\n#### Rug\n\nRaw data can be shown with a **rug**, i.e. ticks on the axes that mark where the data is.\n\nYou can add a rug with `geom_rug()`.\n:::\n\n::: callout-note\n#### Quiz 1\n\nWhat can you notice about the distribution of VOT values?\n\n::: {.callout-tip collapse=\"true\"}\n#### Hint\n\nAre there multiple peaks in the distribution?\n:::\n:::\n\n## Filtering data\n\nWe are getting closer and closer to start modelling our VOT data to learn more about them.\n\nNormally, you would approach data modelling by using the entire data set and including as many variables as it makes sense. Since you are just starting to learn how to model data with [brms](https://paul-buerkner.github.io/brms/), we will first take a pedagogical approach and start small.\n\nYou will have noticed in the density plot that there seems to be two groups of data: and you would be right! The data contains VOT values for both voiceless and voiced plosives.\n\nFor now, we will filter the data so that we include *only voiceless plosives that don't have a VOT longer than 20 ms*. (Again, we are doing this for pedagogical reasons, not because this is what you would do with this data in real-life research!).\n\nBefore we can move on onto filtering data, we first need to learn about *logical operators*.\n\n### Logical operators\n\nThere are four main logical operators:\n\n-   `x == y`: `x` equals `y`.\n\n-   `x != y`: `x` is not equal to `y`.\n\n-   `x > y`: `x` is greater than `y`.\n\n-   `x < y`: `x` is smaller than `y`.\n\nLogical operators return `TRUE` or `FALSE` depending on whether the statement they convey is true or false. Remember, `TRUE` and `FALSE` are logical values.\n\nTry these out in the Console:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This will return FALSE\n1 == 2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\n# FALSE\n\"apples\" == \"oranges\"\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\n# TRUE\n10 > 5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n# FALSE\n10 > 15\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\n# TRUE\n3 < 4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n\n::: callout-tip\n#### Logical operators\n\n**Logical operators** are symbols that compare two objects and return either `TRUE` or `FALSE`.\n\nThe most common logical operators are `==`, `!=`, `>`, and `<`.\n:::\n\n::: callout-note\n#### Quiz 2\n\n\na. Which of the following is not a logical operator? <div class='webex-radiogroup' id='radio_DWDFESYAXJ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DWDFESYAXJ\" value=\"\"></input> <span>`3 > 1`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DWDFESYAXJ\" value=\"answer\"></input> <span>`\"a\" = \"a\"`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DWDFESYAXJ\" value=\"\"></input> <span>`\"b\" != \"b\"`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_DWDFESYAXJ\" value=\"\"></input> <span>`19 < 2`</span></label></div>\nb. Which of the following returns `c(FALSE, TRUE)`? <div class='webex-radiogroup' id='radio_TNZFUMZHRI'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TNZFUMZHRI\" value=\"\"></input> <span>`3 > c(1, 5)`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TNZFUMZHRI\" value=\"answer\"></input> <span>`c(\"a\", \"b\") != c(\"a\")`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TNZFUMZHRI\" value=\"\"></input> <span>`\"apple\" != \"apple\"`</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_TNZFUMZHRI\" value=\"\"></input> <span>`c(\"A\", \";\") == c(\"B\", \";\")`</span></label></div>\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hint\n\n**2a.**\n\nCheck for errors in the logical operators.\n\n**2b.**\n\nI tricked you! The first `;` is the Roman semicolon, and the second `;` is the Greek question mark! (Have you copy-pasted from the tutorial? If not, do that!)\n:::\n:::\n\nNow let's see how these work with `filter()`!\n\n### The `filter()` function\n\nFiltering in R with the tidyverse is straightforward. You can use the `filter()` function.\n\n`filter()` takes one or more statements with logical operators.\n\nLet's try this out. The following code filters the `consonant` column so that only the consonant `p` is included.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  filter(consonant == \"p\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"speaker\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"file\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"label\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"release\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"voi_onset\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"consonant\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"vot\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"s01\",\"2\":\"014-pata\",\"3\":\"p\",\"4\":\"0.7045125\",\"5\":\"0.7119728\",\"6\":\"p\",\"7\":\"7.460317\"},{\"1\":\"s01\",\"2\":\"055-pata\",\"3\":\"p\",\"4\":\"0.8228798\",\"5\":\"0.8378685\",\"6\":\"p\",\"7\":\"14.988662\"},{\"1\":\"s01\",\"2\":\"096-pata\",\"3\":\"p\",\"4\":\"1.0979365\",\"5\":\"1.1041723\",\"6\":\"p\",\"7\":\"6.235828\"},{\"1\":\"s02\",\"2\":\"034-pata\",\"3\":\"p\",\"4\":\"0.7236508\",\"5\":\"0.7347166\",\"6\":\"p\",\"7\":\"11.065760\"},{\"1\":\"s02\",\"2\":\"075-pata\",\"3\":\"p\",\"4\":\"0.7039683\",\"5\":\"0.7156689\",\"6\":\"p\",\"7\":\"11.700680\"},{\"1\":\"s02\",\"2\":\"116-pata\",\"3\":\"p\",\"4\":\"0.8964626\",\"5\":\"0.9085488\",\"6\":\"p\",\"7\":\"12.086168\"},{\"1\":\"s04\",\"2\":\"018-pata\",\"3\":\"p\",\"4\":\"0.5024717\",\"5\":\"0.5095465\",\"6\":\"p\",\"7\":\"7.074830\"},{\"1\":\"s04\",\"2\":\"061-pata\",\"3\":\"p\",\"4\":\"0.5928345\",\"5\":\"0.6096145\",\"6\":\"p\",\"7\":\"16.780045\"},{\"1\":\"s04\",\"2\":\"103-pata\",\"3\":\"p\",\"4\":\"0.7218594\",\"5\":\"0.7505896\",\"6\":\"p\",\"7\":\"28.730159\"},{\"1\":\"s05\",\"2\":\"018-pata\",\"3\":\"p\",\"4\":\"0.2732653\",\"5\":\"0.2874376\",\"6\":\"p\",\"7\":\"14.172336\"},{\"1\":\"s05\",\"2\":\"059-pata\",\"3\":\"p\",\"4\":\"0.3743311\",\"5\":\"0.3963265\",\"6\":\"p\",\"7\":\"21.995465\"},{\"1\":\"s05\",\"2\":\"101-pata\",\"3\":\"p\",\"4\":\"0.3839456\",\"5\":\"0.4039683\",\"6\":\"p\",\"7\":\"20.022676\"},{\"1\":\"s06\",\"2\":\"030-pata\",\"3\":\"p\",\"4\":\"0.4586848\",\"5\":\"0.4732880\",\"6\":\"p\",\"7\":\"14.603175\"},{\"1\":\"s06\",\"2\":\"072-pata\",\"3\":\"p\",\"4\":\"0.4290476\",\"5\":\"0.4409524\",\"6\":\"p\",\"7\":\"11.904762\"},{\"1\":\"s06\",\"2\":\"114-pata\",\"3\":\"p\",\"4\":\"0.3619048\",\"5\":\"0.3758050\",\"6\":\"p\",\"7\":\"13.900227\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNeat! What if we want to include *all consonants except* `p`? Easy, we use the non-equal operator `!=`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  filter(consonant != \"p\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"speaker\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"file\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"label\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"release\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"voi_onset\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"consonant\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"vot\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"s01\",\"2\":\"001-cica\",\"3\":\"ts\",\"4\":\"1.6449206\",\"5\":\"1.74306122\",\"6\":\"ts\",\"7\":\"98.140590\"},{\"1\":\"s01\",\"2\":\"002-bari\",\"3\":\"b\",\"4\":\"0.4556689\",\"5\":\"0.35190476\",\"6\":\"b\",\"7\":\"-103.764172\"},{\"1\":\"s01\",\"2\":\"004-gati\",\"3\":\"g\",\"4\":\"0.8180726\",\"5\":\"0.68893424\",\"6\":\"ɡ\",\"7\":\"-129.138322\"},{\"1\":\"s01\",\"2\":\"011-kati\",\"3\":\"k\",\"4\":\"0.7539456\",\"5\":\"0.78539683\",\"6\":\"k\",\"7\":\"31.451247\"},{\"1\":\"s01\",\"2\":\"020-tapa\",\"3\":\"t\",\"4\":\"0.8247166\",\"5\":\"0.83272109\",\"6\":\"t\",\"7\":\"8.004535\"},{\"1\":\"s01\",\"2\":\"022-data\",\"3\":\"d\",\"4\":\"0.8550794\",\"5\":\"0.76741497\",\"6\":\"d\",\"7\":\"-87.664399\"},{\"1\":\"s01\",\"2\":\"026-xixa\",\"3\":\"dz\",\"4\":\"0.7801134\",\"5\":\"0.67580499\",\"6\":\"dz\",\"7\":\"-104.308390\"},{\"1\":\"s01\",\"2\":\"027-5aji\",\"3\":\"tS\",\"4\":\"0.8429252\",\"5\":\"0.91736961\",\"6\":\"tʃ\",\"7\":\"74.444444\"},{\"1\":\"s01\",\"2\":\"029-gjaku\",\"3\":\"J\",\"4\":\"0.9600907\",\"5\":\"0.86213152\",\"6\":\"d̻ʒ̻\",\"7\":\"-97.959184\"},{\"1\":\"s01\",\"2\":\"030-qava\",\"3\":\"c\",\"4\":\"0.9275510\",\"5\":\"1.01764172\",\"6\":\"t̻ʃ̻\",\"7\":\"90.090703\"},{\"1\":\"s01\",\"2\":\"037-xhaja\",\"3\":\"dZ\",\"4\":\"0.7642630\",\"5\":\"0.66038549\",\"6\":\"dʒ\",\"7\":\"-103.877551\"},{\"1\":\"s01\",\"2\":\"042-cica\",\"3\":\"ts\",\"4\":\"3.9090476\",\"5\":\"3.99605442\",\"6\":\"ts\",\"7\":\"87.006803\"},{\"1\":\"s01\",\"2\":\"043-bari\",\"3\":\"b\",\"4\":\"0.8066213\",\"5\":\"0.72201814\",\"6\":\"b\",\"7\":\"-84.603175\"},{\"1\":\"s01\",\"2\":\"045-gati\",\"3\":\"g\",\"4\":\"1.0112472\",\"5\":\"0.89997732\",\"6\":\"ɡ\",\"7\":\"-111.269841\"},{\"1\":\"s01\",\"2\":\"052-kati\",\"3\":\"k\",\"4\":\"0.7723129\",\"5\":\"0.80734694\",\"6\":\"k\",\"7\":\"35.034014\"},{\"1\":\"s01\",\"2\":\"061-tapa\",\"3\":\"t\",\"4\":\"0.9443311\",\"5\":\"0.95294785\",\"6\":\"t\",\"7\":\"8.616780\"},{\"1\":\"s01\",\"2\":\"063-data\",\"3\":\"d\",\"4\":\"0.9553061\",\"5\":\"0.83083900\",\"6\":\"d\",\"7\":\"-124.467120\"},{\"1\":\"s01\",\"2\":\"068-xixa\",\"3\":\"dz\",\"4\":\"0.7226304\",\"5\":\"0.62195011\",\"6\":\"dz\",\"7\":\"-100.680272\"},{\"1\":\"s01\",\"2\":\"069-5aji\",\"3\":\"tS\",\"4\":\"0.6364399\",\"5\":\"0.69759637\",\"6\":\"tʃ\",\"7\":\"61.156463\"},{\"1\":\"s01\",\"2\":\"071-gjaku\",\"3\":\"J\",\"4\":\"0.8603401\",\"5\":\"0.77562358\",\"6\":\"d̻ʒ̻\",\"7\":\"-84.716553\"},{\"1\":\"s01\",\"2\":\"072-qava\",\"3\":\"c\",\"4\":\"0.7148526\",\"5\":\"0.78031746\",\"6\":\"t̻ʃ̻\",\"7\":\"65.464853\"},{\"1\":\"s01\",\"2\":\"079-xhaja\",\"3\":\"dZ\",\"4\":\"0.9422676\",\"5\":\"0.83759637\",\"6\":\"dʒ\",\"7\":\"-104.671202\"},{\"1\":\"s01\",\"2\":\"083-cica\",\"3\":\"ts\",\"4\":\"2.3342404\",\"5\":\"2.42308390\",\"6\":\"ts\",\"7\":\"88.843537\"},{\"1\":\"s01\",\"2\":\"084-bari\",\"3\":\"b\",\"4\":\"0.7083900\",\"5\":\"0.60142857\",\"6\":\"b\",\"7\":\"-106.961451\"},{\"1\":\"s01\",\"2\":\"086-gati\",\"3\":\"g\",\"4\":\"0.9669841\",\"5\":\"0.88643991\",\"6\":\"ɡ\",\"7\":\"-80.544218\"},{\"1\":\"s01\",\"2\":\"093-kati\",\"3\":\"k\",\"4\":\"0.9079819\",\"5\":\"0.94607710\",\"6\":\"k\",\"7\":\"38.095238\"},{\"1\":\"s01\",\"2\":\"102-tapa\",\"3\":\"t\",\"4\":\"0.9509524\",\"5\":\"0.96401361\",\"6\":\"t\",\"7\":\"13.061224\"},{\"1\":\"s01\",\"2\":\"104-data\",\"3\":\"d\",\"4\":\"1.1672562\",\"5\":\"1.04916100\",\"6\":\"d\",\"7\":\"-118.095238\"},{\"1\":\"s01\",\"2\":\"109-xixa\",\"3\":\"dz\",\"4\":\"0.8648073\",\"5\":\"0.92918367\",\"6\":\"dz\",\"7\":\"64.376417\"},{\"1\":\"s01\",\"2\":\"110-5aji\",\"3\":\"tS\",\"4\":\"0.8689116\",\"5\":\"0.94675737\",\"6\":\"tʃ\",\"7\":\"77.845805\"},{\"1\":\"s01\",\"2\":\"112-gjaku\",\"3\":\"J\",\"4\":\"0.8815646\",\"5\":\"0.75804989\",\"6\":\"d̻ʒ̻\",\"7\":\"-123.514739\"},{\"1\":\"s01\",\"2\":\"113-qava\",\"3\":\"c\",\"4\":\"0.9263039\",\"5\":\"1.01693878\",\"6\":\"t̻ʃ̻\",\"7\":\"90.634921\"},{\"1\":\"s01\",\"2\":\"120-xhaja\",\"3\":\"dZ\",\"4\":\"0.7680726\",\"5\":\"0.65242630\",\"6\":\"dʒ\",\"7\":\"-115.646259\"},{\"1\":\"s02\",\"2\":\"001-5aji\",\"3\":\"tS\",\"4\":\"2.1101361\",\"5\":\"2.21827664\",\"6\":\"tʃ\",\"7\":\"108.140590\"},{\"1\":\"s02\",\"2\":\"003-xhaja\",\"3\":\"dZ\",\"4\":\"0.7507483\",\"5\":\"0.66766440\",\"6\":\"dʒ\",\"7\":\"-83.083900\"},{\"1\":\"s02\",\"2\":\"008-data\",\"3\":\"d\",\"4\":\"0.6731746\",\"5\":\"0.55299320\",\"6\":\"d\",\"7\":\"-120.181406\"},{\"1\":\"s02\",\"2\":\"011-tapa\",\"3\":\"t\",\"4\":\"0.7521315\",\"5\":\"0.76603175\",\"6\":\"t\",\"7\":\"13.900227\"},{\"1\":\"s02\",\"2\":\"017-cica\",\"3\":\"ts\",\"4\":\"0.5758957\",\"5\":\"0.65820862\",\"6\":\"ts\",\"7\":\"82.312925\"},{\"1\":\"s02\",\"2\":\"020-kati\",\"3\":\"k\",\"4\":\"0.6957823\",\"5\":\"0.75065760\",\"6\":\"k\",\"7\":\"54.875283\"},{\"1\":\"s02\",\"2\":\"023-gjaku\",\"3\":\"J\",\"4\":\"0.7116780\",\"5\":\"0.60959184\",\"6\":\"d̻ʒ̻\",\"7\":\"-102.086168\"},{\"1\":\"s02\",\"2\":\"024-qava\",\"3\":\"c\",\"4\":\"0.5778458\",\"5\":\"0.70424036\",\"6\":\"t̻ʃ̻\",\"7\":\"126.394558\"},{\"1\":\"s02\",\"2\":\"031-gati\",\"3\":\"g\",\"4\":\"0.6533560\",\"5\":\"0.54811791\",\"6\":\"ɡ\",\"7\":\"-105.238095\"},{\"1\":\"s02\",\"2\":\"035-xixa\",\"3\":\"dz\",\"4\":\"0.6855556\",\"5\":\"0.58471655\",\"6\":\"dz\",\"7\":\"-100.839002\"},{\"1\":\"s02\",\"2\":\"039-bari\",\"3\":\"b\",\"4\":\"0.7480272\",\"5\":\"0.63344671\",\"6\":\"b\",\"7\":\"-114.580499\"},{\"1\":\"s02\",\"2\":\"042-5aji\",\"3\":\"tS\",\"4\":\"2.2436961\",\"5\":\"2.33671202\",\"6\":\"tʃ\",\"7\":\"93.015873\"},{\"1\":\"s02\",\"2\":\"044-xhaja\",\"3\":\"dZ\",\"4\":\"0.6359637\",\"5\":\"0.53995465\",\"6\":\"dʒ\",\"7\":\"-96.009070\"},{\"1\":\"s02\",\"2\":\"049-data\",\"3\":\"d\",\"4\":\"0.6419501\",\"5\":\"0.54233560\",\"6\":\"d\",\"7\":\"-99.614512\"},{\"1\":\"s02\",\"2\":\"052-tapa\",\"3\":\"t\",\"4\":\"0.7002268\",\"5\":\"0.71117914\",\"6\":\"t\",\"7\":\"10.952381\"},{\"1\":\"s02\",\"2\":\"058-cica\",\"3\":\"ts\",\"4\":\"0.6390249\",\"5\":\"0.70532880\",\"6\":\"ts\",\"7\":\"66.303855\"},{\"1\":\"s02\",\"2\":\"061-kati\",\"3\":\"k\",\"4\":\"0.6082540\",\"5\":\"0.65233560\",\"6\":\"k\",\"7\":\"44.081633\"},{\"1\":\"s02\",\"2\":\"064-gjaku\",\"3\":\"J\",\"4\":\"0.7730612\",\"5\":\"0.62294785\",\"6\":\"d̻ʒ̻\",\"7\":\"-150.113379\"},{\"1\":\"s02\",\"2\":\"065-qava\",\"3\":\"c\",\"4\":\"0.6428798\",\"5\":\"0.72315193\",\"6\":\"t̻ʃ̻\",\"7\":\"80.272109\"},{\"1\":\"s02\",\"2\":\"072-gati\",\"3\":\"g\",\"4\":\"0.6448980\",\"5\":\"0.51913832\",\"6\":\"ɡ\",\"7\":\"-125.759637\"},{\"1\":\"s02\",\"2\":\"076-xixa\",\"3\":\"dz\",\"4\":\"0.6471882\",\"5\":\"0.52097506\",\"6\":\"dz\",\"7\":\"-126.213152\"},{\"1\":\"s02\",\"2\":\"080-bari\",\"3\":\"b\",\"4\":\"0.7995011\",\"5\":\"0.65680272\",\"6\":\"b\",\"7\":\"-142.698413\"},{\"1\":\"s02\",\"2\":\"083-5aji\",\"3\":\"tS\",\"4\":\"1.5513605\",\"5\":\"1.62927438\",\"6\":\"tʃ\",\"7\":\"77.913832\"},{\"1\":\"s02\",\"2\":\"085-xhaja\",\"3\":\"dZ\",\"4\":\"0.6534694\",\"5\":\"0.56954649\",\"6\":\"dʒ\",\"7\":\"-83.922902\"},{\"1\":\"s02\",\"2\":\"090-data\",\"3\":\"d\",\"4\":\"0.6147619\",\"5\":\"0.50439909\",\"6\":\"d\",\"7\":\"-110.362812\"},{\"1\":\"s02\",\"2\":\"093-tapa\",\"3\":\"t\",\"4\":\"0.8278685\",\"5\":\"0.83839002\",\"6\":\"t\",\"7\":\"10.521542\"},{\"1\":\"s02\",\"2\":\"099-cica\",\"3\":\"ts\",\"4\":\"0.6250794\",\"5\":\"0.70866213\",\"6\":\"ts\",\"7\":\"83.582766\"},{\"1\":\"s02\",\"2\":\"102-kati\",\"3\":\"k\",\"4\":\"0.7340816\",\"5\":\"0.78251701\",\"6\":\"k\",\"7\":\"48.435374\"},{\"1\":\"s02\",\"2\":\"105-gjaku\",\"3\":\"J\",\"4\":\"0.7736961\",\"5\":\"0.67775510\",\"6\":\"d̻ʒ̻\",\"7\":\"-95.941043\"},{\"1\":\"s02\",\"2\":\"106-qava\",\"3\":\"c\",\"4\":\"0.6063039\",\"5\":\"0.73934240\",\"6\":\"t̻ʃ̻\",\"7\":\"133.038549\"},{\"1\":\"s02\",\"2\":\"113-gati\",\"3\":\"g\",\"4\":\"0.6989116\",\"5\":\"0.59117914\",\"6\":\"ɡ\",\"7\":\"-107.732426\"},{\"1\":\"s02\",\"2\":\"117-xixa\",\"3\":\"dz\",\"4\":\"0.6820862\",\"5\":\"0.57575964\",\"6\":\"dz\",\"7\":\"-106.326531\"},{\"1\":\"s02\",\"2\":\"121-bari\",\"3\":\"b\",\"4\":\"0.7731066\",\"5\":\"0.60095238\",\"6\":\"b\",\"7\":\"-172.154195\"},{\"1\":\"s04\",\"2\":\"001-data\",\"3\":\"d\",\"4\":\"0.8127891\",\"5\":\"0.68959184\",\"6\":\"d\",\"7\":\"-123.197279\"},{\"1\":\"s04\",\"2\":\"002-gjaku\",\"3\":\"J\",\"4\":\"0.7213152\",\"5\":\"0.66208617\",\"6\":\"d̻ʒ̻\",\"7\":\"-59.229025\"},{\"1\":\"s04\",\"2\":\"005-xhaja\",\"3\":\"dZ\",\"4\":\"0.6819955\",\"5\":\"0.59324263\",\"6\":\"dʒ\",\"7\":\"-88.752834\"},{\"1\":\"s04\",\"2\":\"010-tapa\",\"3\":\"t\",\"4\":\"0.5601361\",\"5\":\"0.57002268\",\"6\":\"t\",\"7\":\"9.886621\"},{\"1\":\"s04\",\"2\":\"011-xixa\",\"3\":\"dz\",\"4\":\"0.6019501\",\"5\":\"0.55632653\",\"6\":\"dz\",\"7\":\"-45.623583\"},{\"1\":\"s04\",\"2\":\"014-cica\",\"3\":\"ts\",\"4\":\"0.6415420\",\"5\":\"0.73834467\",\"6\":\"ts\",\"7\":\"96.802721\"},{\"1\":\"s04\",\"2\":\"020-5aji\",\"3\":\"tS\",\"4\":\"0.6264853\",\"5\":\"0.72392290\",\"6\":\"tʃ\",\"7\":\"97.437642\"},{\"1\":\"s04\",\"2\":\"026-bari\",\"3\":\"b\",\"4\":\"0.6126077\",\"5\":\"0.51478458\",\"6\":\"b\",\"7\":\"-97.823129\"},{\"1\":\"s04\",\"2\":\"030-gati\",\"3\":\"g\",\"4\":\"0.6453968\",\"5\":\"0.57088435\",\"6\":\"ɡ\",\"7\":\"-74.512472\"},{\"1\":\"s04\",\"2\":\"036-kati\",\"3\":\"k\",\"4\":\"0.6048299\",\"5\":\"0.64065760\",\"6\":\"k\",\"7\":\"35.827664\"},{\"1\":\"s04\",\"2\":\"038-qava\",\"3\":\"c\",\"4\":\"0.5175057\",\"5\":\"0.63625850\",\"6\":\"t̻ʃ̻\",\"7\":\"118.752834\"},{\"1\":\"s04\",\"2\":\"043-data\",\"3\":\"d\",\"4\":\"7.9499773\",\"5\":\"7.80877551\",\"6\":\"d\",\"7\":\"-141.201814\"},{\"1\":\"s04\",\"2\":\"044-gjaku\",\"3\":\"J\",\"4\":\"0.4180045\",\"5\":\"0.34226757\",\"6\":\"d̻ʒ̻\",\"7\":\"-75.736961\"},{\"1\":\"s04\",\"2\":\"047-xhaja\",\"3\":\"dZ\",\"4\":\"0.4984127\",\"5\":\"0.42634921\",\"6\":\"dʒ\",\"7\":\"-72.063492\"},{\"1\":\"s04\",\"2\":\"053-tapa\",\"3\":\"t\",\"4\":\"0.5162585\",\"5\":\"0.52507937\",\"6\":\"t\",\"7\":\"8.820862\"},{\"1\":\"s04\",\"2\":\"054-xixa\",\"3\":\"dz\",\"4\":\"0.5465306\",\"5\":\"0.43589569\",\"6\":\"dz\",\"7\":\"-110.634921\"},{\"1\":\"s04\",\"2\":\"057-cica\",\"3\":\"ts\",\"4\":\"0.4720181\",\"5\":\"0.57514739\",\"6\":\"ts\",\"7\":\"103.129252\"},{\"1\":\"s04\",\"2\":\"063-5aji\",\"3\":\"tS\",\"4\":\"0.5360998\",\"5\":\"0.62385488\",\"6\":\"tʃ\",\"7\":\"87.755102\"},{\"1\":\"s04\",\"2\":\"069-bari\",\"3\":\"b\",\"4\":\"0.5658503\",\"5\":\"0.46138322\",\"6\":\"b\",\"7\":\"-104.467120\"},{\"1\":\"s04\",\"2\":\"073-gati\",\"3\":\"g\",\"4\":\"0.5610204\",\"5\":\"0.46482993\",\"6\":\"ɡ\",\"7\":\"-96.190476\"},{\"1\":\"s04\",\"2\":\"080-kati\",\"3\":\"k\",\"4\":\"0.5037188\",\"5\":\"0.56458050\",\"6\":\"k\",\"7\":\"60.861678\"},{\"1\":\"s04\",\"2\":\"082-qava\",\"3\":\"c\",\"4\":\"0.5163265\",\"5\":\"0.66410431\",\"6\":\"t̻ʃ̻\",\"7\":\"147.777778\"},{\"1\":\"s04\",\"2\":\"085-data\",\"3\":\"d\",\"4\":\"3.6822676\",\"5\":\"3.54609977\",\"6\":\"d\",\"7\":\"-136.167800\"},{\"1\":\"s04\",\"2\":\"086-gjaku\",\"3\":\"J\",\"4\":\"0.5182540\",\"5\":\"0.42195011\",\"6\":\"d̻ʒ̻\",\"7\":\"-96.303855\"},{\"1\":\"s04\",\"2\":\"089-xhaja\",\"3\":\"dZ\",\"4\":\"0.6464853\",\"5\":\"0.57827664\",\"6\":\"dʒ\",\"7\":\"-68.208617\"},{\"1\":\"s04\",\"2\":\"095-tapa\",\"3\":\"t\",\"4\":\"0.8013605\",\"5\":\"0.81512472\",\"6\":\"t\",\"7\":\"13.764172\"},{\"1\":\"s04\",\"2\":\"096-xixa\",\"3\":\"dz\",\"4\":\"0.6068481\",\"5\":\"0.50766440\",\"6\":\"dz\",\"7\":\"-99.183673\"},{\"1\":\"s04\",\"2\":\"099-cica\",\"3\":\"ts\",\"4\":\"0.4767800\",\"5\":\"0.57192744\",\"6\":\"ts\",\"7\":\"95.147392\"},{\"1\":\"s04\",\"2\":\"105-5aji\",\"3\":\"tS\",\"4\":\"0.7132880\",\"5\":\"0.80709751\",\"6\":\"tʃ\",\"7\":\"93.809524\"},{\"1\":\"s04\",\"2\":\"110-bari\",\"3\":\"b\",\"4\":\"0.5357823\",\"5\":\"0.42814059\",\"6\":\"b\",\"7\":\"-107.641723\"},{\"1\":\"s04\",\"2\":\"114-gati\",\"3\":\"g\",\"4\":\"0.5497506\",\"5\":\"0.48755102\",\"6\":\"ɡ\",\"7\":\"-62.199546\"},{\"1\":\"s04\",\"2\":\"122-kati\",\"3\":\"k\",\"4\":\"0.6009070\",\"5\":\"0.65240363\",\"6\":\"k\",\"7\":\"51.496599\"},{\"1\":\"s04\",\"2\":\"124-qava\",\"3\":\"c\",\"4\":\"0.5635147\",\"5\":\"0.67070295\",\"6\":\"t̻ʃ̻\",\"7\":\"107.188209\"},{\"1\":\"s05\",\"2\":\"003-qava\",\"3\":\"c\",\"4\":\"0.2115873\",\"5\":\"0.35746032\",\"6\":\"t̻ʃ̻\",\"7\":\"145.873016\"},{\"1\":\"s05\",\"2\":\"013-data\",\"3\":\"d\",\"4\":\"0.2444671\",\"5\":\"0.08582766\",\"6\":\"d\",\"7\":\"-158.639456\"},{\"1\":\"s05\",\"2\":\"014-xixa\",\"3\":\"dz\",\"4\":\"0.2067120\",\"5\":\"0.07866213\",\"6\":\"dz\",\"7\":\"-128.049887\"},{\"1\":\"s05\",\"2\":\"016-kati\",\"3\":\"k\",\"4\":\"0.1117007\",\"5\":\"0.22272109\",\"6\":\"k\",\"7\":\"111.020408\"},{\"1\":\"s05\",\"2\":\"020-xhaja\",\"3\":\"dZ\",\"4\":\"0.3634014\",\"5\":\"0.27643991\",\"6\":\"dʒ\",\"7\":\"-86.961451\"},{\"1\":\"s05\",\"2\":\"022-5aji\",\"3\":\"tS\",\"4\":\"0.3500680\",\"5\":\"0.46403628\",\"6\":\"tʃ\",\"7\":\"113.968254\"},{\"1\":\"s05\",\"2\":\"024-gjaku\",\"3\":\"J\",\"4\":\"0.3020181\",\"5\":\"0.22541950\",\"6\":\"d̻ʒ̻\",\"7\":\"-76.598639\"},{\"1\":\"s05\",\"2\":\"030-tapa\",\"3\":\"t\",\"4\":\"0.2062132\",\"5\":\"0.23197279\",\"6\":\"t\",\"7\":\"25.759637\"},{\"1\":\"s05\",\"2\":\"032-gati\",\"3\":\"g\",\"4\":\"0.2538549\",\"5\":\"0.12952381\",\"6\":\"ɡ\",\"7\":\"-124.331066\"},{\"1\":\"s05\",\"2\":\"036-bari\",\"3\":\"b\",\"4\":\"0.3567120\",\"5\":\"0.25081633\",\"6\":\"b\",\"7\":\"-105.895692\"},{\"1\":\"s05\",\"2\":\"039-cica\",\"3\":\"ts\",\"4\":\"0.2292063\",\"5\":\"0.32800454\",\"6\":\"ts\",\"7\":\"98.798186\"},{\"1\":\"s05\",\"2\":\"044-qava\",\"3\":\"c\",\"4\":\"0.3180952\",\"5\":\"0.45181406\",\"6\":\"t̻ʃ̻\",\"7\":\"133.718821\"},{\"1\":\"s05\",\"2\":\"054-data\",\"3\":\"d\",\"4\":\"0.4672336\",\"5\":\"0.33997732\",\"6\":\"d\",\"7\":\"-127.256236\"},{\"1\":\"s05\",\"2\":\"055-xixa\",\"3\":\"dz\",\"4\":\"0.4258277\",\"5\":\"0.33467120\",\"6\":\"dz\",\"7\":\"-91.156463\"},{\"1\":\"s05\",\"2\":\"057-kati\",\"3\":\"k\",\"4\":\"0.4306122\",\"5\":\"0.52038549\",\"6\":\"k\",\"7\":\"89.773243\"},{\"1\":\"s05\",\"2\":\"061-xhaja\",\"3\":\"dZ\",\"4\":\"0.4382766\",\"5\":\"0.25820862\",\"6\":\"dʒ\",\"7\":\"-180.068027\"},{\"1\":\"s05\",\"2\":\"063-5aji\",\"3\":\"tS\",\"4\":\"0.4538549\",\"5\":\"0.59439909\",\"6\":\"tʃ\",\"7\":\"140.544218\"},{\"1\":\"s05\",\"2\":\"065-gjaku\",\"3\":\"J\",\"4\":\"0.3634014\",\"5\":\"0.26539683\",\"6\":\"d̻ʒ̻\",\"7\":\"-98.004535\"},{\"1\":\"s05\",\"2\":\"071-tapa\",\"3\":\"t\",\"4\":\"0.3966667\",\"5\":\"0.41868481\",\"6\":\"t\",\"7\":\"22.018141\"},{\"1\":\"s05\",\"2\":\"073-gati\",\"3\":\"g\",\"4\":\"0.5317914\",\"5\":\"0.40521542\",\"6\":\"ɡ\",\"7\":\"-126.575964\"},{\"1\":\"s05\",\"2\":\"078-bari\",\"3\":\"b\",\"4\":\"0.3877098\",\"5\":\"0.26170068\",\"6\":\"b\",\"7\":\"-126.009070\"},{\"1\":\"s05\",\"2\":\"081-cica\",\"3\":\"ts\",\"4\":\"0.3556916\",\"5\":\"0.44730159\",\"6\":\"ts\",\"7\":\"91.609977\"},{\"1\":\"s05\",\"2\":\"086-qava\",\"3\":\"c\",\"4\":\"0.2789116\",\"5\":\"0.40918367\",\"6\":\"t̻ʃ̻\",\"7\":\"130.272109\"},{\"1\":\"s05\",\"2\":\"096-data\",\"3\":\"d\",\"4\":\"0.4184807\",\"5\":\"0.30385488\",\"6\":\"d\",\"7\":\"-114.625850\"},{\"1\":\"s05\",\"2\":\"097-xixa\",\"3\":\"dz\",\"4\":\"0.3665079\",\"5\":\"0.26616780\",\"6\":\"dz\",\"7\":\"-100.340136\"},{\"1\":\"s05\",\"2\":\"099-kati\",\"3\":\"k\",\"4\":\"0.3512925\",\"5\":\"0.45718821\",\"6\":\"k\",\"7\":\"105.895692\"},{\"1\":\"s05\",\"2\":\"103-xhaja\",\"3\":\"dZ\",\"4\":\"0.4359637\",\"5\":\"0.30412698\",\"6\":\"dʒ\",\"7\":\"-131.836735\"},{\"1\":\"s05\",\"2\":\"105-5aji\",\"3\":\"tS\",\"4\":\"0.3382766\",\"5\":\"0.49267574\",\"6\":\"tʃ\",\"7\":\"154.399093\"},{\"1\":\"s05\",\"2\":\"107-gjaku\",\"3\":\"J\",\"4\":\"0.3573243\",\"5\":\"0.25947846\",\"6\":\"d̻ʒ̻\",\"7\":\"-97.845805\"},{\"1\":\"s05\",\"2\":\"113-tapa\",\"3\":\"t\",\"4\":\"0.2995011\",\"5\":\"0.34687075\",\"6\":\"t\",\"7\":\"47.369615\"},{\"1\":\"s05\",\"2\":\"115-gati\",\"3\":\"g\",\"4\":\"0.3017234\",\"5\":\"0.15287982\",\"6\":\"ɡ\",\"7\":\"-148.843537\"},{\"1\":\"s05\",\"2\":\"120-bari\",\"3\":\"b\",\"4\":\"0.2897279\",\"5\":\"0.16292517\",\"6\":\"b\",\"7\":\"-126.802721\"},{\"1\":\"s05\",\"2\":\"123-cica\",\"3\":\"ts\",\"4\":\"0.2833333\",\"5\":\"0.35691610\",\"6\":\"ts\",\"7\":\"73.582766\"},{\"1\":\"s06\",\"2\":\"003-xhaja\",\"3\":\"dZ\",\"4\":\"0.5511791\",\"5\":\"0.45562358\",\"6\":\"dʒ\",\"7\":\"-95.555556\"},{\"1\":\"s06\",\"2\":\"004-xixa\",\"3\":\"dz\",\"4\":\"0.5296825\",\"5\":\"0.44408163\",\"6\":\"dz\",\"7\":\"-85.600907\"},{\"1\":\"s06\",\"2\":\"005-gjaku\",\"3\":\"J\",\"4\":\"0.4929478\",\"5\":\"0.38897959\",\"6\":\"d̻ʒ̻\",\"7\":\"-103.968254\"},{\"1\":\"s06\",\"2\":\"010-data\",\"3\":\"d\",\"4\":\"0.4885488\",\"5\":\"0.38759637\",\"6\":\"d\",\"7\":\"-100.952381\"},{\"1\":\"s06\",\"2\":\"020-bari\",\"3\":\"b\",\"4\":\"0.5565533\",\"5\":\"0.47530612\",\"6\":\"b\",\"7\":\"-81.247166\"},{\"1\":\"s06\",\"2\":\"021-5aji\",\"3\":\"tS\",\"4\":\"0.5247846\",\"5\":\"0.60034014\",\"6\":\"tʃ\",\"7\":\"75.555556\"},{\"1\":\"s06\",\"2\":\"022-gati\",\"3\":\"g\",\"4\":\"0.7220862\",\"5\":\"0.61886621\",\"6\":\"ɡ\",\"7\":\"-103.219955\"},{\"1\":\"s06\",\"2\":\"024-kati\",\"3\":\"k\",\"4\":\"0.5097279\",\"5\":\"0.54099773\",\"6\":\"k\",\"7\":\"31.269841\"},{\"1\":\"s06\",\"2\":\"025-cica\",\"3\":\"ts\",\"4\":\"0.4403628\",\"5\":\"0.51873016\",\"6\":\"ts\",\"7\":\"78.367347\"},{\"1\":\"s06\",\"2\":\"032-tapa\",\"3\":\"t\",\"4\":\"0.5454875\",\"5\":\"0.55780045\",\"6\":\"t\",\"7\":\"12.312925\"},{\"1\":\"s06\",\"2\":\"033-qava\",\"3\":\"c\",\"4\":\"0.5471655\",\"5\":\"0.60961451\",\"6\":\"t̻ʃ̻\",\"7\":\"62.448980\"},{\"1\":\"s06\",\"2\":\"045-xhaja\",\"3\":\"dZ\",\"4\":\"0.4974150\",\"5\":\"0.40448980\",\"6\":\"dʒ\",\"7\":\"-92.925170\"},{\"1\":\"s06\",\"2\":\"046-xixa\",\"3\":\"dz\",\"4\":\"0.4966893\",\"5\":\"0.39643991\",\"6\":\"dz\",\"7\":\"-100.249433\"},{\"1\":\"s06\",\"2\":\"047-gjaku\",\"3\":\"J\",\"4\":\"0.7109977\",\"5\":\"0.62521542\",\"6\":\"d̻ʒ̻\",\"7\":\"-85.782313\"},{\"1\":\"s06\",\"2\":\"052-data\",\"3\":\"d\",\"4\":\"0.5193878\",\"5\":\"0.41403628\",\"6\":\"d\",\"7\":\"-105.351474\"},{\"1\":\"s06\",\"2\":\"062-bari\",\"3\":\"b\",\"4\":\"0.6053288\",\"5\":\"0.52253968\",\"6\":\"b\",\"7\":\"-82.789116\"},{\"1\":\"s06\",\"2\":\"063-5aji\",\"3\":\"tS\",\"4\":\"0.5797732\",\"5\":\"0.65433107\",\"6\":\"tʃ\",\"7\":\"74.557823\"},{\"1\":\"s06\",\"2\":\"064-gati\",\"3\":\"g\",\"4\":\"0.4695918\",\"5\":\"0.38231293\",\"6\":\"ɡ\",\"7\":\"-87.278912\"},{\"1\":\"s06\",\"2\":\"066-kati\",\"3\":\"k\",\"4\":\"0.4571429\",\"5\":\"0.49879819\",\"6\":\"k\",\"7\":\"41.655329\"},{\"1\":\"s06\",\"2\":\"067-cica\",\"3\":\"ts\",\"4\":\"0.5683900\",\"5\":\"0.62965986\",\"6\":\"ts\",\"7\":\"61.269841\"},{\"1\":\"s06\",\"2\":\"074-tapa\",\"3\":\"t\",\"4\":\"0.5694785\",\"5\":\"0.58321995\",\"6\":\"t\",\"7\":\"13.741497\"},{\"1\":\"s06\",\"2\":\"075-qava\",\"3\":\"c\",\"4\":\"0.6925624\",\"5\":\"0.75913832\",\"6\":\"t̻ʃ̻\",\"7\":\"66.575964\"},{\"1\":\"s06\",\"2\":\"087-xhaja\",\"3\":\"dZ\",\"4\":\"0.4139683\",\"5\":\"0.32009070\",\"6\":\"dʒ\",\"7\":\"-93.877551\"},{\"1\":\"s06\",\"2\":\"088-xixa\",\"3\":\"dz\",\"4\":\"0.5272789\",\"5\":\"0.42698413\",\"6\":\"dz\",\"7\":\"-100.294785\"},{\"1\":\"s06\",\"2\":\"089-gjaku\",\"3\":\"J\",\"4\":\"0.5707029\",\"5\":\"0.49818594\",\"6\":\"d̻ʒ̻\",\"7\":\"-72.517007\"},{\"1\":\"s06\",\"2\":\"094-data\",\"3\":\"d\",\"4\":\"0.5653515\",\"5\":\"0.47476190\",\"6\":\"d\",\"7\":\"-90.589569\"},{\"1\":\"s06\",\"2\":\"104-bari\",\"3\":\"b\",\"4\":\"0.4743311\",\"5\":\"0.41038549\",\"6\":\"b\",\"7\":\"-63.945578\"},{\"1\":\"s06\",\"2\":\"105-5aji\",\"3\":\"tS\",\"4\":\"1.6635601\",\"5\":\"1.72605442\",\"6\":\"tʃ\",\"7\":\"62.494331\"},{\"1\":\"s06\",\"2\":\"106-gati\",\"3\":\"g\",\"4\":\"0.4508390\",\"5\":\"0.34678005\",\"6\":\"ɡ\",\"7\":\"-104.058957\"},{\"1\":\"s06\",\"2\":\"108-kati\",\"3\":\"k\",\"4\":\"0.4065306\",\"5\":\"0.44709751\",\"6\":\"k\",\"7\":\"40.566893\"},{\"1\":\"s06\",\"2\":\"109-cica\",\"3\":\"ts\",\"4\":\"0.5708844\",\"5\":\"0.65673469\",\"6\":\"ts\",\"7\":\"85.850340\"},{\"1\":\"s06\",\"2\":\"116-tapa\",\"3\":\"t\",\"4\":\"0.4992517\",\"5\":\"0.51204082\",\"6\":\"t\",\"7\":\"12.789116\"},{\"1\":\"s06\",\"2\":\"117-qava\",\"3\":\"c\",\"4\":\"0.8373016\",\"5\":\"0.89791383\",\"6\":\"t̻ʃ̻\",\"7\":\"60.612245\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nAnd if we want only `k` from speaker `s02`? We can include multiple statements separated by a comma!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  filter(consonant == \"k\", speaker == \"s02\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"speaker\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"file\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"label\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"release\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"voi_onset\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"consonant\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"vot\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"s02\",\"2\":\"020-kati\",\"3\":\"k\",\"4\":\"0.6957823\",\"5\":\"0.7506576\",\"6\":\"k\",\"7\":\"54.87528\"},{\"1\":\"s02\",\"2\":\"061-kati\",\"3\":\"k\",\"4\":\"0.6082540\",\"5\":\"0.6523356\",\"6\":\"k\",\"7\":\"44.08163\"},{\"1\":\"s02\",\"2\":\"102-kati\",\"3\":\"k\",\"4\":\"0.7340816\",\"5\":\"0.7825170\",\"6\":\"k\",\"7\":\"48.43537\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nCombining statements like this will give you only those rows where both conditions apply. You can add as many statements as you need.\n\nNow try to filter the data so that you include only speaker `s04` and VOT values that are shorter than 20 ms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  filter(...)\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hint\n\nDo you remember the logical operator for \"smaller than\"?\n:::\n\nThis is all great, but what if we want to include multiple consonants?\n\nTo do that we need another operator: `%in%`.\n\n### The `%in%` operator\n\n::: callout-tip\n#### `%in%`\n\nThe `%in%` operator is a special logical operator that returns `TRUE` if the value to the left of the operator is one of the values in the vector to its right, and `FALSE` if not.\n:::\n\nTry these in the Console:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TRUE\n5 %in% c(1, 2, 5, 7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n# FALSE\n\"apples\" %in% c(\"oranges\", \"bananas\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\n\nBut `%in%` is even more powerful because the value on the left does not have to be a single value, but it can also be a vector! We say `%in%` is *vectorised* because it can work with vectors (most functions and operators in R are vectorised).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# TRUE, TRUE\nc(1, 5) %in% c(4, 1, 7, 5, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE TRUE\n```\n:::\n\n```{.r .cell-code}\nstocked <- c(\"durian\", \"bananas\", \"grapes\")\nneeded <- c(\"durian\", \"apples\")\n\n# TRUE, FALSE\nneeded %in% stocked\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  TRUE FALSE\n```\n:::\n:::\n\n\nTry to understand what is going on in the code above before moving on.\n\n### Now filter the data\n\nNow we can filter `alb_vot` to include only the voiceless plosives `p, t, k` and VOT values smaller than 20 ms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot_vl <- alb_vot %>%\n  filter(\n    consonant %in% c(\"p\", \"t\", \"k\"),\n    vot < 20\n  )\n```\n:::\n\n\nThis should not look too alien! The first statement, `consonant %in% c(\"p\", \"t\", \"k\")` looks at the `consonant` column and, for each row, it returns `TRUE` if the current row value is in `c(\"p\", \"t\", \"k\")`, and `FALSE` if not.\n\n::: {.callout-warning collapse=\"true\"}\n## Explanation\n\nIf it's not very clear what is going on, try the following code.\n\n``` r\nalb_vless <- alb_vot %>%\n  mutate(voiceless = consonant %in% c(\"p\", \"t\", \"k\"))\nalb_vless\n\nalb_vless %>%\n  filter(voiceless == TRUE)\n```\n:::\n\nThe second statement, `vot < 20`, filters in VOT values that are less than 20 ms.\n\nYou might have noticed that we need to assign the output of `filter()`, which is a data frame, to a new variable `alb_vot_vl` (\"vl\" for \"voiceless\"). This will be the data frame you will use in the next section.\n\n## Modelling with `brm()`\n\nIn the lecture, we have seen that we can assume voiceless VOT values to be distributed according to a Gaussian distribution (you may also have encountered Gaussian distributions under the name \"normal distribution\").\n\n$$vot \\sim Gaussian(\\mu, \\sigma)$$\n\nWe can calculate the sample mean and standard deviation easily, using the `summarise()` function, as you learnt in Week 2. Go ahead and complete the code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot_vl %>%\n  summarise(\n    ...\n  )\n```\n:::\n\n\nBut now we want to make inference from our sample (N = 24) to the entire population of VOT values of the Albanian voiceless plosives /p/, /t/, /k/.\n\nWe want to estimate the following probability distributions and parameters:\n\n$$\n\\begin{align}\nvot & \\sim Gaussian(\\mu, \\sigma) \\\\\n\\mu & \\sim Gaussian(\\mu_1, \\sigma_1) \\\\\n\\sigma & \\sim TruncGaussian(\\mu_2, \\sigma_2)\n\\end{align}\n$$\n\nIn other words, we are trying to estimate the following hyperparameters: $\\mu_1$, $\\sigma_1$, $\\mu_2$, $\\sigma_2$.\n\nWe can achieve this by modelling the data using the `brm()` function from the brms package (BRM stands for Bayesian Regression Model). We will go into more details about what this means in the weeks to follow. For now, note that regression is a synonym of linear model, a type of modelling approach that you are learning in this course.\n\nAdd `library(brms)` in the `setup` chunk and run that chunk again so that the brms package is attached. Then, run the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot_bm <- brm(\n  vot ~ 1,\n  family = gaussian(),\n  data = alb_vot_vl,\n  backend = \"cmdstanr\"\n)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\nYou will see the message `Compiling Stan program...` followed by `Start sampling`. Something like in the figure below.\n\n![](/img/mcmc-messages.png)\n\nWe will get back to what all this means in the coming weeks. For now know that [Stan](https://mc-stan.org) is a programming language that can run Bayesian models. `brm()` is an R interface to Stan, so that you can use R and R syntax to run Bayesian models without having to learn Stan! (If you feel adventurous, nobody stops you from learning Stan too, although it is not required for this course).\n\nThe \"sampling\" part is about the Markov-Chain Monte Carlo (or MCMC) sampling algorithm. For a quick intro on MCMC, check the Extra box below.\n\n::: {.callout-important collapse=\"true\"}\n#### Extra: Markov-Chain Monte Carlo\n\n::: {.callout-tip icon=\"false\"}\n#### MCMC\n\nMarkov-Chain Monte Carlo refers to a set of algorithms used to estimate parameters of unknown distributions, based on repeated draws from parameter values and observed data.\n:::\n\nYou can read a more extended explanation by Elizabeth Pankratz [here](https://elizabethpankratz.github.io/bayes_stat/day1/mcmc.html).\n\nYou don't need to understand the details of this. For now, just remember that several draws are made (i.e. the algorithm is run for several iterations), and that the model runs 4 chains of these iterations.\n\nWe will learn more about chains and iterations in the coming weeks and you will know how to use information about these to diagnose the robustness of the estimated parameters.\n:::\n\n### Model summary\n\nNow we can inspect the model output using the `summary()` function (don't confuse this with the `summarise()` function, used to get statistical summaries of data).\n\n::: callout-warning\nThe summary *might look* something like this, but don't worry if your numbers are slightly different from these!\n\nThat happens due to the randomness inherent in the MCMC sampling process.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(alb_vot_bm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: vot ~ 1 \n   Data: alb_vot_vl (Number of observations: 24) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nPopulation-Level Effects: \n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept    11.62      0.59    10.48    12.78 1.00     2559     2158\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     2.88      0.44     2.18     3.88 1.00     2327     2013\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n\nWe have seen the summary of this model during the lecture. Do you remember how to interpret it?\n\n::: callout-note\n#### Quiz 3\n\n\na. The 95% CrI of $\\mu$ (`Intercept`) includes 12.9. <select class='webex-select'><option value='blank'></option><option value=''>TRUE</option><option value='answer'>FALSE</option></select> \n\nb. The standard deviation $\\sigma_2$ of $\\sigma$ (`sigma`) is 0.44 <select class='webex-select'><option value='blank'></option><option value='answer'>TRUE</option><option value=''>FALSE</option></select>\n\n:::\n\nYou can use the `tidy()` function from the [broom.mixed](https://github.com/bbolker/broom.mixed) package to extract the information on the estimated parameters as a table (remember to attach the package in the `setup` chunk; you might also need to install the package).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(alb_vot_bm)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"effect\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"component\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"group\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"term\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std.error\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.low\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.high\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"fixed\",\"2\":\"cond\",\"3\":\"NA\",\"4\":\"(Intercept)\",\"5\":\"11.615214\",\"6\":\"0.5918518\",\"7\":\"10.475890\",\"8\":\"12.784235\"},{\"1\":\"ran_pars\",\"2\":\"cond\",\"3\":\"Residual\",\"4\":\"sd__Observation\",\"5\":\"2.875128\",\"6\":\"0.4369244\",\"7\":\"2.175595\",\"8\":\"3.876583\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe `term` column gives us the two main parameters we wanted to estimate:\n\n-   `(Intercept)` is actually $\\mu$.\n\n-   `sd__Observation` is $\\sigma$.\n\nNote that `sd__Observation` in the tidy table corresponds to `sigma` in the model summary above.\n\nNow, for each of the two parameters, you get `estimate` and `std.error`. There are the hyperparameters of the probability distributions for $\\mu$ and $\\sigma$.\n\n-   `(Intercept)` ($\\mu$): `estimate` is $\\mu_1$: 11.62 ms, `std.error` is $\\sigma_1$: 0.57 ms.\n\n-   `sd__Observation` ($\\sigma$): `estimate` is $\\mu_2$: 2.86 ms, `std.error` is $\\sigma_2$: 0.44 ms.\n\nIn notation:\n\n$$\n\\begin{align}\nvot & \\sim Gaussian(\\mu, \\sigma) \\\\\n\\mu & \\sim Gaussian(11.62, 0.57) \\\\\n\\sigma & \\sim TruncGaussian(2.86, 0.44)\n\\end{align}\n$$\n\nBased on the model summary and on the tidy summary, we also know the **95% Credible Intervals** (CrIs) of the probability distributions of $\\mu$ and $sigma$. They are in the columns of the tidy summary called `conf.low` and `conf.high`.\n\n::: {.callout-tip icon=\"false\"}\n#### Credible Interval\n\nA **95% (Bayesian) Credible Interval** indicates that we can be **95% confident** that the true parameter value is within that interval.\n\nYou can also say that there is a **95% probability** that the true parameter value is within that interval.\n:::\n\n-   At 95% confidence, the mean ($\\mu$) VOT value for Albanian voiceless stops is between 10.48 and 12.78 ms.\n\n-   As for the standard deviation ($\\sigma$), we can be 95% confident that it is between 2.18 and 3.88 ms.\n\nYou can also say:\n\n-   There is a 95% probability that the mean ($\\mu$) VOT value for Albanian voiceless stops is between 10.48 and 12.78 ms.\n\n-   As for the standard deviation ($\\sigma$), there is a 95% probabilty that it is between 2.18 and 3.88 ms.\n\n::: {.callout-important collapse=\"true\"}\n## Extra: Frequentist Confidence Intervals\n\nIf you are familiar with or have heard of Confidence Intervals, these are not the same as Credible Intervals (even though we talk about *confidence* when talking about Credible Intervals.\n\nCredible Intervals are *Bayesian*, while Confidence Intervals are *frequentist* (remember we mentioned the frequentist and Bayesian views of probabilities in class?).\n\nIf you want to know more about frequentist Confidence Intervals, check this web app: \\<<https://rpsychologist.com/d3/ci/>\\>.\n\nFunnily enough, even experienced researchers don't really understand frequentist Confidence Intervals and tend to interpret them as Bayesian Credible Intervals. Check this paper for more info: [Robust misinterpretation of confidence intervals](https://link.springer.com/article/10.3758/s13423-013-0572-3).\n:::\n\n### Reporting\n\nHow would you report all that?\n\nReporting statistical models is quite formulaic, so you can use the following as a template and replace values as needed when you need to report other models.\n\n> We fitted a Bayesian model of the VOT of Albanian voiceless plosive, using a Gaussian distribution as the distribution family of the model. According to the model, there is a 95% probability that the VOT mean is between 10.48 and 12.78 ms ($\\beta$ = 11.6, SD = 0.59), and there is a 95% probability that the VOT SD is between 2.18 and 3.88 ($\\beta$ = 2.87, SD = 0.43).\n\nIt is common to report both the CrIs and the estimate and standard deviation of each parameter.\n\nIt is also helpful to visualise probability distributions by plotting probability densities. You will learn how to do this next week!\n\nIn the meantime, read on to find out how to create violin plots and customise your plots!\n\n## Violin plots\n\nAn efficient way of showing the distribution of continuous variables depending on discrete groups (like `consonant`) are the so-called **violin plots**.\n\nGo ahead and run the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(consonant, vot)) +\n  geom_violin()\n```\n\n::: {.cell-output-display}\n![](tutorial-w04_files/figure-html/vot-consonant-1.png){width=672}\n:::\n:::\n\n\nThey are called violin plots because they look like violins! The geometry for violin plots is... `geom_violin()`.\n\nUsually, you need the following `aes`thetics:\n\n-   `x`-axis: a categorical variable, like `consonant`.\n\n-   `y`-axis: a continuous numeric variable, like `vot`.\n\n### Lay over the raw data\n\nYou can lay over raw data on top of the violins. To do so, you can use the `jitter` geometry.\n\n`geom_jitter()` creates so-called strip charts. Let's first see how these look like without violins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(consonant, vot)) +\n  geom_jitter()\n```\n\n::: {.cell-output-display}\n![](tutorial-w04_files/figure-html/vot-jitter-1.png){width=672}\n:::\n:::\n\n\nThat doesn't look great right? The points are spread too wide.\n\nWe can fix that by specifying the argument `width` in the jitter geometry to be something smaller than `0.5`. Try a few values until you think it looks better.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(consonant, vot)) +\n  geom_jitter(width = ...)\n```\n:::\n\n\nWhen you are satisfied, create a violin plot with overlaid strip charts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(consonant, vot)) +\n  geom_violin() +\n  geom_jitter(width = ...)\n```\n:::\n\n\nNote that the order between the violin and jitter geometries is important. If you add the jitter geometry before the violin geometry, the violins will just cover the jittered points (see why it is called \"layered\" grammar of graphics?).\n\nNow, try to create a violin and strip chart plot so that each `speaker` is plotted separately on the *y*-axis instead of `consonant`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nNormally, the violins are vertical (meaning, that `speaker` would be on the *x*-axis), but here I ask to create a plot with `speaker` on the *y*-axis!\n\nYou can achieve this by inverting the axes aesthetics (i.e. `x` and `y`) in `aes()`.\n:::\n\n### If-else\n\nIt's clear from this last plot where each speaker is plotted separately that there are two subgroups of consonants: there are voiced and voiceless consonants (and you have also noticed this in the density plot above).\n\nSo, what if we want to plot voiceless and voiced consonants separately?\n\nWe can use faceting, as you learnt in Week 3, or we can use the aesthetics `fill` and/or `colour`. However, first we need to create a new column that indicates if a consonant is voiceless or voiced!\n\nWe will use the `mutate()` function to create a new `voicing` column. But how do we get the values for this new column (without having to manually code each row as voiceless or voiced)?\n\nWe can use the `ifelse()` function!\n\nThe `ifelse()` function works a bit like the English sentence \"If X is true, do Y, otherwise do Z\". The \"X\" has to be a logical statement, i.e. an expression using the logical operators you learnt above.\n\nLook at the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nifelse(10 > 9, \"correct!\", \"wrong...\")\n```\n:::\n\n\nYou can read that as: If `10 > 9` is `TRUE`, then return `correct!`, if it's `FALSE`, then return `wrong...`.\n\nWhat will that code return? Think about this and then try the code to see that you got it right.\n\n`ifelse()` is vectorised, so you can even test multiple values, like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nifelse(c(1, 3, 10) > 9, \"correct!\", \"wrong...\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"wrong...\" \"wrong...\" \"correct!\"\n```\n:::\n:::\n\n\nWe get `wrong...` for `1 > 9` and `3 > 9`, and `correct!` for `10 > 9`.\n\nYou can even use `%in%`!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nifelse(c(\"apple\", \"banana\", \"cherry\") %in% c(\"apple\", \"durian\", \"passion fruit\"), \"got it!\", \"need to buy\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"got it!\"     \"need to buy\" \"need to buy\"\n```\n:::\n:::\n\n\nWe will use `ifelse()` in conjunction with `mutate()` to create a new column `voicing`. But first, we need to get the list of consonants in the data set!\n\n(You could find these manually, but why do so when you can automate things with code?)\n\n### Finding unique values\n\nSo, the data contains the following consonants:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncons_ipa <- alb_vot$consonant\n\nunique(cons_ipa)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"ts\" \"b\"  \"ɡ\"  \"k\"  \"p\"  \"t\"  \"d\"  \"dz\" \"tʃ\" \"d̻ʒ̻\" \"t̻ʃ̻\" \"dʒ\"\n```\n:::\n:::\n\n\nWait, what's that `$` in `alb_vot$consonant` there? That is a base R way of extracting a single column (in this case `consonant`) from a data frame (`alb_vot`).\n\n::: callout-tip\n#### The dollar sign \\`\\$\\`\n\nYou can use the dollar sign `$` to extract a single column from a data frame as a vector.\n:::\n\nIf you check `cons_ipa` in the Environment tab, it will say that this is `chr` vector, i.e. a character vector. This makes sense, because `consonant` is a character column in `alb_vot`.\n\n::: callout-tip\n#### Find unique values\n\nThe `unique()` function shows the unique values of a vector (it works with any type of vector, numeric, character, logical, ...).\n:::\n\nThis is great, we now know all the consonants in the `consonant` column, but maybe it will be easier to type them later if we use the custom transcription in `label` rather than IPA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncons_lab <- alb_vot$label\n\nunique(cons_lab)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"ts\" \"b\"  \"g\"  \"k\"  \"p\"  \"t\"  \"d\"  \"dz\" \"tS\" \"J\"  \"c\"  \"dZ\"\n```\n:::\n:::\n\n\nGreat! Now, to make things easier, let me tell you which consonants are voiceless and which are voiced:\n\n-   voiceless: `c(\"ts\", \"k\", \"p\", \"t\", \"tS\", \"c\")`.\n\n-   voiced: `c(\"b\", \"g\", \"d\", \"dz\", \"J\", \"dZ\")`.\n\nNow with this knowledge we can create a new column with `voiceless` and `voiced` values for each row in the data frame. Like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot <- alb_vot %>%\n  mutate(\n    voicing = ifelse(\n      # IF this is TRUE\n      label %in% c(\"ts\", \"k\", \"p\", \"t\", \"tS\", \"c\"),\n      # Write\n      \"voiceless\",\n      # OR ELSE write\n      \"voiced\"\n    )\n  )\n```\n:::\n\n\nThe `ifelse()` function is doing the following:\n\n-   If the value in the column `label` is among (`%in%`) the values in the vector `c(\"ts\", \"k\", \"p\", \"t\", \"tS\", \"c\")`.\n\n-   Write `voiceless` in the `voicing` column.\n\n-   Otherwise write `voiced`.\n\nCheck out the `voicing` column in `alb_vot`.\n\nNow that we have the info we need to plot voiceless and voiced consonants separately, let's do that!\n\n### Plotting voiceless and voiced VOT\n\nGo ahead and fill in the code to create a plot with violins and overlayed strip chart with `voicing` on the *x*-axis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(...) +\n  ...\n```\n:::\n\n\nYou should get the following:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](tutorial-w04_files/figure-html/vot-vio-jitt-voi-1.png){width=672}\n:::\n:::\n\n\n### Let's add some colour\n\nLet's **fill** the violins with colour. For now, just colour the violins depending on `voicing`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(voicing, vot, ...)) +\n  geom_violin() +\n  geom_jitter(width = 0.05)\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hint\n\nUse the `fill` aesthetic in `aes()`.\n:::\n\nYou should get this:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](tutorial-w04_files/figure-html/vot-vio-jit-2-1.png){width=672}\n:::\n:::\n\n\nNot bad! But maybe we can improve by making the fill a bit transparent?\n\nYou can achieve that with the `alpha` argument in `geom_violin()`, which takes a number between 0 (completely transparent) and 1 (completely opaque).\n\nAdd it to the code above to make the fill transparent. Try different values until you are satisfied with the output. You could also add `alpha` to `geom_jitter()` to make the points a bit transparent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(voicing, vot, fill = voicing)) +\n  geom_violin(...) +\n  geom_jitter(width = 0.05)\n```\n:::\n\n\nWonderful! Now, what can you tell about VOT in voiceless and voiced consonants in Albanian based on this plot?\n\nNext week we will learn how to model variables depending on different groups!\n\nBut for now, let's talk about legends and labels.\n\n## Legends and labels in plots\n\n### Plot titles and labels\n\nThe `labs()` function allows you to set the plot title, subtitle, axis labels and more.\n\nSince these are strings (i.e. text), they must be quoted with `\"\"`. Replace the `...` below with an appropriate title, like `\"VOT of Albanian stops\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(voicing, vot, fill = voicing)) +\n  geom_violin() +\n  geom_jitter(width = 0.05, alpha = 0.2) +\n  labs(\n    title = ...\n  )\n```\n:::\n\n\n### Axis labels\n\nTo change the the axis labels, you can specify a string for `x` and `y` in the `labs()` function.\n\nI have changed the `x` label here below. Go ahead and change `y` to `\"VOT (ms)\"`. (Remember to also add the title).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(voicing, vot, fill = voicing)) +\n  geom_violin() +\n  geom_jitter(width = 0.05, alpha = 0.2) +\n  labs(\n    title = ...,\n    x = \"Consonant voicing\",\n    ...\n  )\n```\n:::\n\n\n### Positioning the legend\n\nThe position of the legend can be set with the `legend.position` argument in the `theme()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(voicing, vot, fill = voicing)) +\n  geom_violin() +\n  geom_jitter(width = 0.05, alpha = 0.2) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](tutorial-w04_files/figure-html/vot-legend-1.png){width=672}\n:::\n:::\n\n\nSometimes you don't want the legend at all. You can achieve that with `\"none\"` as the value to the `legend.position` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalb_vot %>%\n  ggplot(aes(voicing, vot, fill = voicing)) +\n  geom_violin() +\n  geom_jitter(width = 0.05, alpha = 0.2) +\n  theme(legend.position = ...)\n```\n:::\n\n\n## Summary\n\n::: {.callout-note appearance=\"minimal\"}\n**Transforming data**\n\n-   `mutate()` creates new columns or mutates existing ones.\n\n-   `filter()` can filter data based on given values.\n\n-   With `ifelse()`, you can output values depending on a logical statement.\n\n-   Use logical operators to create logical statements: `==`, `!=`, `>`, `<`.\n\n-   `unique()` returns the unique values of a vector.\n\n-   The `%in%` operator returns `TRUE` if the value on the operator's left-hand side is one of the values in the vector on the right-hand side, and `FALSE` if not.\n\n**Plotting**\n\n-   Use `geom_density()` to create density plots.\n\n-   Use `geom_violin()` to create violin plots.\n\n-   Use `geom_jitter()` to create strip charts.\n\n-   `labs()` allows you to specify title and axis labels.\n\n-   `theme(legend.position = …)` lets you specify the position of the legend.\n\n**Modelling**\n\n-   Use `brm()` with `family = gaussian()` to model the mean and standard deviation of Gaussian data.\n\n-   `summary()` returns the summary of a `brm` model.\n\n-   With `tidy()` from broom.mixed you can obtain a tidy table with the model summary.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}